
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action InicioAction;

	private global::Gtk.Action ProductosAction;

	private global::Gtk.Action SalirAction;

	private global::Gtk.Action GestionarProductosAction;

	private global::Gtk.Action GestionarTiposDeProductosAction;

	private global::Gtk.Action GestionarMovimientosAction;

	private global::Gtk.Action RealizarMovimientoAction;

	private global::Gtk.Action HistorialAction;

	private global::Gtk.Action FacturaAction;

	private global::Gtk.Action RealizarFacturaAction;

	private global::Gtk.Action HistorialAction1;

	private global::Gtk.Action DoctoresAction;

	private global::Gtk.Action GestionarDoctoresAction;

	private global::Gtk.Action GestionarEspecialidadesAction;

	private global::Gtk.VBox vbox1;

	private global::Gtk.MenuBar menubar1;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.InicioAction = new global::Gtk.Action("InicioAction", global::Mono.Unix.Catalog.GetString("Inicio"), null, null);
		this.InicioAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Inicio");
		w1.Add(this.InicioAction, null);
		this.ProductosAction = new global::Gtk.Action("ProductosAction", global::Mono.Unix.Catalog.GetString("Productos"), null, null);
		this.ProductosAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Prueba");
		w1.Add(this.ProductosAction, null);
		this.SalirAction = new global::Gtk.Action("SalirAction", global::Mono.Unix.Catalog.GetString("Salir"), null, null);
		this.SalirAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Salir");
		w1.Add(this.SalirAction, null);
		this.GestionarProductosAction = new global::Gtk.Action("GestionarProductosAction", global::Mono.Unix.Catalog.GetString("Gestionar productos"), null, null);
		this.GestionarProductosAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Gestionar productos");
		w1.Add(this.GestionarProductosAction, null);
		this.GestionarTiposDeProductosAction = new global::Gtk.Action("GestionarTiposDeProductosAction", global::Mono.Unix.Catalog.GetString("Gestionar tipos de productos"), null, null);
		this.GestionarTiposDeProductosAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Gestionar tipos de productos");
		w1.Add(this.GestionarTiposDeProductosAction, null);
		this.GestionarMovimientosAction = new global::Gtk.Action("GestionarMovimientosAction", global::Mono.Unix.Catalog.GetString("Gestionar movimientos"), null, null);
		this.GestionarMovimientosAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Gestionar movimientos");
		w1.Add(this.GestionarMovimientosAction, null);
		this.RealizarMovimientoAction = new global::Gtk.Action("RealizarMovimientoAction", global::Mono.Unix.Catalog.GetString("Realizar movimiento"), null, null);
		this.RealizarMovimientoAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Realizar movimiento");
		w1.Add(this.RealizarMovimientoAction, null);
		this.HistorialAction = new global::Gtk.Action("HistorialAction", global::Mono.Unix.Catalog.GetString("Historial"), null, null);
		this.HistorialAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Historial");
		w1.Add(this.HistorialAction, null);
		this.FacturaAction = new global::Gtk.Action("FacturaAction", global::Mono.Unix.Catalog.GetString("Factura"), null, null);
		this.FacturaAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Factura");
		w1.Add(this.FacturaAction, null);
		this.RealizarFacturaAction = new global::Gtk.Action("RealizarFacturaAction", global::Mono.Unix.Catalog.GetString("Realizar factura"), null, null);
		this.RealizarFacturaAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Realizar factura");
		w1.Add(this.RealizarFacturaAction, null);
		this.HistorialAction1 = new global::Gtk.Action("HistorialAction1", global::Mono.Unix.Catalog.GetString("Historial"), null, null);
		this.HistorialAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("Historial");
		w1.Add(this.HistorialAction1, null);
		this.DoctoresAction = new global::Gtk.Action("DoctoresAction", global::Mono.Unix.Catalog.GetString("Doctores"), null, null);
		this.DoctoresAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Doctores");
		w1.Add(this.DoctoresAction, null);
		this.GestionarDoctoresAction = new global::Gtk.Action("GestionarDoctoresAction", global::Mono.Unix.Catalog.GetString("Gestionar doctores"), null, null);
		this.GestionarDoctoresAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Gestionar doctores");
		w1.Add(this.GestionarDoctoresAction, null);
		this.GestionarEspecialidadesAction = new global::Gtk.Action("GestionarEspecialidadesAction", global::Mono.Unix.Catalog.GetString("Gestionar especialidades"), null, null);
		this.GestionarEspecialidadesAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Gestionar especialidades");
		w1.Add(this.GestionarEspecialidadesAction, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString(@"<ui><menubar name='menubar1'><menu name='InicioAction' action='InicioAction'><menuitem name='SalirAction' action='SalirAction'/></menu><menu name='ProductosAction' action='ProductosAction'><menuitem name='GestionarProductosAction' action='GestionarProductosAction'/><menu name='GestionarMovimientosAction' action='GestionarMovimientosAction'><menuitem name='RealizarMovimientoAction' action='RealizarMovimientoAction'/><menuitem name='HistorialAction' action='HistorialAction'/></menu></menu><menu name='DoctoresAction' action='DoctoresAction'><menuitem name='GestionarDoctoresAction' action='GestionarDoctoresAction'/><menuitem name='GestionarEspecialidadesAction' action='GestionarEspecialidadesAction'/></menu><menu name='FacturaAction' action='FacturaAction'><menuitem name='RealizarFacturaAction' action='RealizarFacturaAction'/><menuitem name='HistorialAction1' action='HistorialAction1'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add(this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 667;
		this.DefaultHeight = 305;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.SalirAction.Activated += new global::System.EventHandler(this.OnSalirActionActivated);
		this.GestionarProductosAction.Activated += new global::System.EventHandler(this.OnGestionarProductosActionActivated);
		this.RealizarMovimientoAction.Activated += new global::System.EventHandler(this.OnRealizarMovimientoActionActivated);
		this.HistorialAction.Activated += new global::System.EventHandler(this.OnHistorialActionActivated);
		this.RealizarFacturaAction.Activated += new global::System.EventHandler(this.OnRealizarFacturaActionActivated);
		this.HistorialAction1.Activated += new global::System.EventHandler(this.OnHistorialAction1Activated);
		this.GestionarDoctoresAction.Activated += new global::System.EventHandler(this.OnGestionarDoctoresActionActivated);
		this.GestionarEspecialidadesAction.Activated += new global::System.EventHandler(this.OnGestionarEspecialidadesActionActivated);
	}
}
