
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action InicioAction;

	private global::Gtk.Action ProductosAction;

	private global::Gtk.Action SalirAction;

	private global::Gtk.Action GestionarProductosAction;

	private global::Gtk.Action GestionarTiposDeProductosAction;

	private global::Gtk.Action GestionarMovimientosAction;

	private global::Gtk.Action RealizarMovimientoAction;

	private global::Gtk.Action HistorialAction;

	private global::Gtk.Action FacturaAction;

	private global::Gtk.Action RealizarFacturaAction;

	private global::Gtk.Action HistorialAction1;

	private global::Gtk.Action DoctoresAction;

	private global::Gtk.Action GestionarDoctoresAction;

	private global::Gtk.Action GestionarEspecialidadesAction;

	private global::Gtk.Action EspecialidadAction;

	private global::Gtk.Action GestionarEspecialidadesAction1;

	private global::Gtk.Action AsignarEspecialidadAction;

	private global::Gtk.Action PacientesAction;

	private global::Gtk.Action GestionarPacientesAction;

	private global::Gtk.Action CitaAction;

	private global::Gtk.Action RealizarCitaAction;

	private global::Gtk.Action GestionarCitasAction;

	private global::Gtk.Action RealizarCitaAction1;

	private global::Gtk.Action GestionarCitasAction1;

	private global::Gtk.Action SeguridadAction;

	private global::Gtk.Action GestionDeUsuariosAction;

	private global::Gtk.Action GestionDeRolesAction;

	private global::Gtk.Action AsignarRolesAction;

	private global::Gtk.Action GestionDeOpcionesAction;

	private global::Gtk.VBox vbox1;

	private global::Gtk.MenuBar menubar1;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
		this.InicioAction = new global::Gtk.Action("InicioAction", global::Mono.Unix.Catalog.GetString("Inicio"), null, null);
		this.InicioAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Inicio");
		w1.Add(this.InicioAction, null);
		this.ProductosAction = new global::Gtk.Action("ProductosAction", global::Mono.Unix.Catalog.GetString("Productos"), null, null);
		this.ProductosAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Prueba");
		w1.Add(this.ProductosAction, null);
		this.SalirAction = new global::Gtk.Action("SalirAction", global::Mono.Unix.Catalog.GetString("Salir"), null, null);
		this.SalirAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Salir");
		w1.Add(this.SalirAction, null);
		this.GestionarProductosAction = new global::Gtk.Action("GestionarProductosAction", global::Mono.Unix.Catalog.GetString("Gestionar productos"), null, null);
		this.GestionarProductosAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Gestionar productos");
		w1.Add(this.GestionarProductosAction, null);
		this.GestionarTiposDeProductosAction = new global::Gtk.Action("GestionarTiposDeProductosAction", global::Mono.Unix.Catalog.GetString("Gestionar tipos de productos"), null, null);
		this.GestionarTiposDeProductosAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Gestionar tipos de productos");
		w1.Add(this.GestionarTiposDeProductosAction, null);
		this.GestionarMovimientosAction = new global::Gtk.Action("GestionarMovimientosAction", global::Mono.Unix.Catalog.GetString("Gestionar movimientos"), null, null);
		this.GestionarMovimientosAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Gestionar movimientos");
		w1.Add(this.GestionarMovimientosAction, null);
		this.RealizarMovimientoAction = new global::Gtk.Action("RealizarMovimientoAction", global::Mono.Unix.Catalog.GetString("Realizar movimiento"), null, null);
		this.RealizarMovimientoAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Realizar movimiento");
		w1.Add(this.RealizarMovimientoAction, null);
		this.HistorialAction = new global::Gtk.Action("HistorialAction", global::Mono.Unix.Catalog.GetString("Historial"), null, null);
		this.HistorialAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Historial");
		w1.Add(this.HistorialAction, null);
		this.FacturaAction = new global::Gtk.Action("FacturaAction", global::Mono.Unix.Catalog.GetString("Factura"), null, null);
		this.FacturaAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Factura");
		w1.Add(this.FacturaAction, null);
		this.RealizarFacturaAction = new global::Gtk.Action("RealizarFacturaAction", global::Mono.Unix.Catalog.GetString("Realizar factura"), null, null);
		this.RealizarFacturaAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Realizar factura");
		w1.Add(this.RealizarFacturaAction, null);
		this.HistorialAction1 = new global::Gtk.Action("HistorialAction1", global::Mono.Unix.Catalog.GetString("Historial"), null, null);
		this.HistorialAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("Historial");
		w1.Add(this.HistorialAction1, null);
		this.DoctoresAction = new global::Gtk.Action("DoctoresAction", global::Mono.Unix.Catalog.GetString("Doctores"), null, null);
		this.DoctoresAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Doctores");
		w1.Add(this.DoctoresAction, null);
		this.GestionarDoctoresAction = new global::Gtk.Action("GestionarDoctoresAction", global::Mono.Unix.Catalog.GetString("Gestionar doctores"), null, null);
		this.GestionarDoctoresAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Gestionar doctores");
		w1.Add(this.GestionarDoctoresAction, null);
		this.GestionarEspecialidadesAction = new global::Gtk.Action("GestionarEspecialidadesAction", global::Mono.Unix.Catalog.GetString("Gestionar especialidades"), null, null);
		this.GestionarEspecialidadesAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Gestionar especialidades");
		w1.Add(this.GestionarEspecialidadesAction, null);
		this.EspecialidadAction = new global::Gtk.Action("EspecialidadAction", global::Mono.Unix.Catalog.GetString("Especialidad"), null, null);
		this.EspecialidadAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Especialidad");
		w1.Add(this.EspecialidadAction, null);
		this.GestionarEspecialidadesAction1 = new global::Gtk.Action("GestionarEspecialidadesAction1", global::Mono.Unix.Catalog.GetString("Gestionar especialidades"), null, null);
		this.GestionarEspecialidadesAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("Gestionar especialidades");
		w1.Add(this.GestionarEspecialidadesAction1, null);
		this.AsignarEspecialidadAction = new global::Gtk.Action("AsignarEspecialidadAction", global::Mono.Unix.Catalog.GetString("Asignar especialidad"), null, null);
		this.AsignarEspecialidadAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Asignar especialidad");
		w1.Add(this.AsignarEspecialidadAction, null);
		this.PacientesAction = new global::Gtk.Action("PacientesAction", global::Mono.Unix.Catalog.GetString("Pacientes"), null, null);
		this.PacientesAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Pacientes");
		w1.Add(this.PacientesAction, null);
		this.GestionarPacientesAction = new global::Gtk.Action("GestionarPacientesAction", global::Mono.Unix.Catalog.GetString("Gestionar Pacientes"), null, null);
		this.GestionarPacientesAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Gestionar Pacientes");
		w1.Add(this.GestionarPacientesAction, null);
		this.CitaAction = new global::Gtk.Action("CitaAction", global::Mono.Unix.Catalog.GetString("Cita"), null, null);
		this.CitaAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Cita");
		w1.Add(this.CitaAction, null);
		this.RealizarCitaAction = new global::Gtk.Action("RealizarCitaAction", global::Mono.Unix.Catalog.GetString("Realizar Cita"), null, null);
		this.RealizarCitaAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Realizar Cita");
		w1.Add(this.RealizarCitaAction, null);
		this.GestionarCitasAction = new global::Gtk.Action("GestionarCitasAction", global::Mono.Unix.Catalog.GetString("Gestionar Citas"), null, null);
		this.GestionarCitasAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Gestionar Citas");
		w1.Add(this.GestionarCitasAction, null);
		this.RealizarCitaAction1 = new global::Gtk.Action("RealizarCitaAction1", global::Mono.Unix.Catalog.GetString("Realizar Cita"), null, null);
		this.RealizarCitaAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("Realizar Cita");
		w1.Add(this.RealizarCitaAction1, null);
		this.GestionarCitasAction1 = new global::Gtk.Action("GestionarCitasAction1", global::Mono.Unix.Catalog.GetString("Gestionar Citas"), null, null);
		this.GestionarCitasAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("Gestionar Citas");
		w1.Add(this.GestionarCitasAction1, null);
		this.SeguridadAction = new global::Gtk.Action("SeguridadAction", global::Mono.Unix.Catalog.GetString("Seguridad"), null, null);
		this.SeguridadAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Seguridad");
		w1.Add(this.SeguridadAction, null);
		this.GestionDeUsuariosAction = new global::Gtk.Action("GestionDeUsuariosAction", global::Mono.Unix.Catalog.GetString("Gestion de usuarios"), null, null);
		this.GestionDeUsuariosAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Gestion de usuarios");
		w1.Add(this.GestionDeUsuariosAction, null);
		this.GestionDeRolesAction = new global::Gtk.Action("GestionDeRolesAction", global::Mono.Unix.Catalog.GetString("Gestion de roles"), null, null);
		this.GestionDeRolesAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Gestion de roles");
		w1.Add(this.GestionDeRolesAction, null);
		this.AsignarRolesAction = new global::Gtk.Action("AsignarRolesAction", global::Mono.Unix.Catalog.GetString("Asignar roles"), null, null);
		this.AsignarRolesAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Asignar roles");
		w1.Add(this.AsignarRolesAction, null);
		this.GestionDeOpcionesAction = new global::Gtk.Action("GestionDeOpcionesAction", global::Mono.Unix.Catalog.GetString("Gestion de opciones"), null, null);
		this.GestionDeOpcionesAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Gestion de opciones");
		w1.Add(this.GestionDeOpcionesAction, null);
		this.UIManager.InsertActionGroup(w1, 0);
		this.AddAccelGroup(this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Medicentro Dental - Menu Principal");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString("<ui><menubar name=\'menubar1\'><menu name=\'InicioAction\' action=\'InicioAction\'><men" +
				"uitem name=\'SalirAction\' action=\'SalirAction\'/></menu><menu name=\'ProductosActio" +
				"n\' action=\'ProductosAction\'><menuitem name=\'GestionarProductosAction\' action=\'Ge" +
				"stionarProductosAction\'/><menu name=\'GestionarMovimientosAction\' action=\'Gestion" +
				"arMovimientosAction\'><menuitem name=\'RealizarMovimientoAction\' action=\'RealizarM" +
				"ovimientoAction\'/><menuitem name=\'HistorialAction\' action=\'HistorialAction\'/></m" +
				"enu></menu><menu name=\'DoctoresAction\' action=\'DoctoresAction\'><menuitem name=\'G" +
				"estionarDoctoresAction\' action=\'GestionarDoctoresAction\'/><menu name=\'Especialid" +
				"adAction\' action=\'EspecialidadAction\'><menuitem name=\'GestionarEspecialidadesAct" +
				"ion1\' action=\'GestionarEspecialidadesAction1\'/><menuitem name=\'AsignarEspecialid" +
				"adAction\' action=\'AsignarEspecialidadAction\'/></menu></menu><menu name=\'Paciente" +
				"sAction\' action=\'PacientesAction\'><menuitem name=\'GestionarPacientesAction\' acti" +
				"on=\'GestionarPacientesAction\'/><menuitem name=\'RealizarCitaAction1\' action=\'Real" +
				"izarCitaAction1\'/><menuitem name=\'GestionarCitasAction1\' action=\'GestionarCitasA" +
				"ction1\'/></menu><menu name=\'FacturaAction\' action=\'FacturaAction\'><menuitem name" +
				"=\'RealizarFacturaAction\' action=\'RealizarFacturaAction\'/><menuitem name=\'Histori" +
				"alAction1\' action=\'HistorialAction1\'/></menu><menu name=\'SeguridadAction\' action" +
				"=\'SeguridadAction\'><menuitem name=\'GestionDeUsuariosAction\' action=\'GestionDeUsu" +
				"ariosAction\'/><menu name=\'GestionDeRolesAction\' action=\'GestionDeRolesAction\'><m" +
				"enuitem name=\'AsignarRolesAction\' action=\'AsignarRolesAction\'/></menu><menuitem " +
				"name=\'GestionDeOpcionesAction\' action=\'GestionDeOpcionesAction\'/></menu></menuba" +
				"r></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add(this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 746;
		this.DefaultHeight = 305;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.SalirAction.Activated += new global::System.EventHandler(this.OnSalirActionActivated);
		this.GestionarProductosAction.Activated += new global::System.EventHandler(this.OnGestionarProductosActionActivated);
		this.RealizarMovimientoAction.Activated += new global::System.EventHandler(this.OnRealizarMovimientoActionActivated);
		this.HistorialAction.Activated += new global::System.EventHandler(this.OnHistorialActionActivated);
		this.RealizarFacturaAction.Activated += new global::System.EventHandler(this.OnRealizarFacturaActionActivated);
		this.HistorialAction1.Activated += new global::System.EventHandler(this.OnHistorialAction1Activated);
		this.GestionarDoctoresAction.Activated += new global::System.EventHandler(this.OnGestionarDoctoresActionActivated);
		//this.GestionarEspecialidadesAction.Activated += new global::System.EventHandler(this.OnGestionarEspecialidadesActionActivated);
		this.GestionarEspecialidadesAction1.Activated += new global::System.EventHandler(this.OnGestionarEspecialidadesAction1Activated);
		this.AsignarEspecialidadAction.Activated += new global::System.EventHandler(this.OnAsignarEspecialidadActionActivated);
		this.GestionarPacientesAction.Activated += new global::System.EventHandler(this.OnGestionarPacientesActionActivated);
		this.RealizarCitaAction1.Activated += new global::System.EventHandler(this.OnRealizarCitaAction1Activated);
		this.GestionarCitasAction1.Activated += new global::System.EventHandler(this.OnGestionarCitasAction1Activated);
		this.GestionDeUsuariosAction.Activated += new global::System.EventHandler(this.OnGestionDeUsuariosActionActivated);
		this.AsignarRolesAction.Activated += new global::System.EventHandler(this.OnAsignarRolesActionActivated);
		this.GestionDeOpcionesAction.Activated += new global::System.EventHandler(this.OnGestionDeOpcionesActionActivated);
	}
}
