
// This file has been generated by the GUI designer. Do not modify.
namespace medicentro
{
	public partial class frmProductos
	{
		private global::Gtk.Fixed fixed1;

		private global::Gtk.Label lblNombre;

		private global::Gtk.Entry txtNombreProd;

		private global::Gtk.Label lblPrecio;

		private global::Gtk.Entry txtPrecio;

		private global::Gtk.Label lblDescripcion;

		private global::Gtk.Entry txtDescripcion;

		private global::Gtk.Label lblTipo;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView tvwProductos;

		private global::Gtk.Button btnGuardar;

		private global::Gtk.Button btnCancelar;

		private global::Gtk.Button btnEliminar;

		private global::Gtk.Label lblStock;

		private global::Gtk.Entry txtStock;

		private global::Gtk.Label lblCantIni;

		private global::Gtk.Entry txtCantIni;

		private global::Gtk.Entry txtBuscar;

		private global::Gtk.Button btnBuscar;

		private global::Gtk.Label lblProd;

		private global::Gtk.ComboBox cbxTipoProd;

		private global::Gtk.Button btnActualizar;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget medicentro.frmProductos
			this.WidthRequest = 800;
			this.HeightRequest = 430;
			this.Name = "medicentro.frmProductos";
			this.Title = global::Mono.Unix.Catalog.GetString("frmProductos");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child medicentro.frmProductos.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.WidthRequest = 800;
			this.fixed1.HeightRequest = 430;
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.lblNombre = new global::Gtk.Label();
			this.lblNombre.Name = "lblNombre";
			this.lblNombre.LabelProp = global::Mono.Unix.Catalog.GetString("Nombre Producto:");
			this.fixed1.Add(this.lblNombre);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblNombre]));
			w1.X = 28;
			w1.Y = 55;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtNombreProd = new global::Gtk.Entry();
			this.txtNombreProd.WidthRequest = 250;
			this.txtNombreProd.CanFocus = true;
			this.txtNombreProd.Name = "txtNombreProd";
			this.txtNombreProd.IsEditable = true;
			this.txtNombreProd.InvisibleChar = '•';
			this.fixed1.Add(this.txtNombreProd);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtNombreProd]));
			w2.X = 162;
			w2.Y = 52;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.lblPrecio = new global::Gtk.Label();
			this.lblPrecio.Name = "lblPrecio";
			this.lblPrecio.LabelProp = global::Mono.Unix.Catalog.GetString("Precio:");
			this.fixed1.Add(this.lblPrecio);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblPrecio]));
			w3.X = 106;
			w3.Y = 94;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtPrecio = new global::Gtk.Entry();
			this.txtPrecio.WidthRequest = 250;
			this.txtPrecio.CanFocus = true;
			this.txtPrecio.Name = "txtPrecio";
			this.txtPrecio.IsEditable = true;
			this.txtPrecio.InvisibleChar = '•';
			this.fixed1.Add(this.txtPrecio);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtPrecio]));
			w4.X = 163;
			w4.Y = 89;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.lblDescripcion = new global::Gtk.Label();
			this.lblDescripcion.Name = "lblDescripcion";
			this.lblDescripcion.LabelProp = global::Mono.Unix.Catalog.GetString("Descripcion:");
			this.fixed1.Add(this.lblDescripcion);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblDescripcion]));
			w5.X = 69;
			w5.Y = 132;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtDescripcion = new global::Gtk.Entry();
			this.txtDescripcion.WidthRequest = 250;
			this.txtDescripcion.CanFocus = true;
			this.txtDescripcion.Name = "txtDescripcion";
			this.txtDescripcion.IsEditable = true;
			this.txtDescripcion.InvisibleChar = '•';
			this.fixed1.Add(this.txtDescripcion);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtDescripcion]));
			w6.X = 164;
			w6.Y = 127;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.lblTipo = new global::Gtk.Label();
			this.lblTipo.Name = "lblTipo";
			this.lblTipo.LabelProp = global::Mono.Unix.Catalog.GetString("Tipo de Producto:");
			this.fixed1.Add(this.lblTipo);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblTipo]));
			w7.X = 458;
			w7.Y = 56;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.tvwProductos = new global::Gtk.TreeView();
			this.tvwProductos.WidthRequest = 750;
			this.tvwProductos.HeightRequest = 150;
			this.tvwProductos.CanFocus = true;
			this.tvwProductos.Name = "tvwProductos";
			this.GtkScrolledWindow.Add(this.tvwProductos);
			this.fixed1.Add(this.GtkScrolledWindow);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.GtkScrolledWindow]));
			w9.X = 23;
			w9.Y = 207;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnGuardar = new global::Gtk.Button();
			this.btnGuardar.CanFocus = true;
			this.btnGuardar.Name = "btnGuardar";
			this.btnGuardar.UseUnderline = true;
			this.btnGuardar.Label = global::Mono.Unix.Catalog.GetString("Guardar");
			this.fixed1.Add(this.btnGuardar);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnGuardar]));
			w10.X = 535;
			w10.Y = 382;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnCancelar = new global::Gtk.Button();
			this.btnCancelar.CanFocus = true;
			this.btnCancelar.Name = "btnCancelar";
			this.btnCancelar.UseUnderline = true;
			this.btnCancelar.Label = global::Mono.Unix.Catalog.GetString("Cancelar");
			this.fixed1.Add(this.btnCancelar);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnCancelar]));
			w11.X = 610;
			w11.Y = 381;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnEliminar = new global::Gtk.Button();
			this.btnEliminar.CanFocus = true;
			this.btnEliminar.Name = "btnEliminar";
			this.btnEliminar.UseUnderline = true;
			this.btnEliminar.Label = global::Mono.Unix.Catalog.GetString("Eliminar");
			this.fixed1.Add(this.btnEliminar);
			global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnEliminar]));
			w12.X = 686;
			w12.Y = 380;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.lblStock = new global::Gtk.Label();
			this.lblStock.Name = "lblStock";
			this.lblStock.LabelProp = global::Mono.Unix.Catalog.GetString("Stock:");
			this.fixed1.Add(this.lblStock);
			global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblStock]));
			w13.X = 537;
			w13.Y = 90;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtStock = new global::Gtk.Entry();
			this.txtStock.CanFocus = true;
			this.txtStock.Name = "txtStock";
			this.txtStock.IsEditable = true;
			this.txtStock.InvisibleChar = '•';
			this.fixed1.Add(this.txtStock);
			global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtStock]));
			w14.X = 597;
			w14.Y = 87;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.lblCantIni = new global::Gtk.Label();
			this.lblCantIni.Name = "lblCantIni";
			this.lblCantIni.LabelProp = global::Mono.Unix.Catalog.GetString("Cantidad Inicial:");
			this.fixed1.Add(this.lblCantIni);
			global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblCantIni]));
			w15.X = 471;
			w15.Y = 127;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtCantIni = new global::Gtk.Entry();
			this.txtCantIni.CanFocus = true;
			this.txtCantIni.Name = "txtCantIni";
			this.txtCantIni.IsEditable = true;
			this.txtCantIni.InvisibleChar = '•';
			this.fixed1.Add(this.txtCantIni);
			global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtCantIni]));
			w16.X = 598;
			w16.Y = 123;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtBuscar = new global::Gtk.Entry();
			this.txtBuscar.WidthRequest = 300;
			this.txtBuscar.CanFocus = true;
			this.txtBuscar.Name = "txtBuscar";
			this.txtBuscar.IsEditable = true;
			this.txtBuscar.InvisibleChar = '•';
			this.fixed1.Add(this.txtBuscar);
			global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtBuscar]));
			w17.X = 20;
			w17.Y = 166;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnBuscar = new global::Gtk.Button();
			this.btnBuscar.WidthRequest = 100;
			this.btnBuscar.CanFocus = true;
			this.btnBuscar.Name = "btnBuscar";
			this.btnBuscar.UseUnderline = true;
			this.btnBuscar.Label = global::Mono.Unix.Catalog.GetString("Buscar");
			this.fixed1.Add(this.btnBuscar);
			global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnBuscar]));
			w18.X = 353;
			w18.Y = 164;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.lblProd = new global::Gtk.Label();
			this.lblProd.Name = "lblProd";
			this.lblProd.LabelProp = global::Mono.Unix.Catalog.GetString("Productos");
			this.fixed1.Add(this.lblProd);
			global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblProd]));
			w19.X = 374;
			w19.Y = 10;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.cbxTipoProd = global::Gtk.ComboBox.NewText();
			this.cbxTipoProd.WidthRequest = 160;
			this.cbxTipoProd.Name = "cbxTipoProd";
			this.fixed1.Add(this.cbxTipoProd);
			global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.cbxTipoProd]));
			w20.X = 598;
			w20.Y = 48;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnActualizar = new global::Gtk.Button();
			this.btnActualizar.CanFocus = true;
			this.btnActualizar.Name = "btnActualizar";
			this.btnActualizar.UseUnderline = true;
			this.btnActualizar.Label = global::Mono.Unix.Catalog.GetString("Actualizar");
			this.fixed1.Add(this.btnActualizar);
			global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnActualizar]));
			w21.X = 451;
			w21.Y = 384;
			this.Add(this.fixed1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 800;
			this.DefaultHeight = 430;
			this.Show();
			this.tvwProductos.CursorChanged += new global::System.EventHandler(this.OnTvwProductosCursorChanged);
			this.btnGuardar.Clicked += new global::System.EventHandler(this.OnBtnGuardarClicked);
			this.btnCancelar.Clicked += new global::System.EventHandler(this.OnBtnCancelarClicked);
			this.btnEliminar.Clicked += new global::System.EventHandler(this.OnBtnEliminarClicked);
			this.txtBuscar.Changed += new global::System.EventHandler(this.OnTxtBuscarChanged);
			this.cbxTipoProd.Changed += new global::System.EventHandler(this.OnCbxTipoProdChanged);
			this.btnActualizar.Clicked += new global::System.EventHandler(this.OnBtnActualizarClicked);
		}
	}
}
