
// This file has been generated by the GUI designer. Do not modify.
namespace medicentro
{
	public partial class frmLogin
	{
		private global::Gtk.Fixed fixed2;

		private global::Gtk.Label lblPass;

		private global::Gtk.Label lblUser;

		private global::Gtk.Entry entry1;

		private global::Gtk.Entry entry2;

		private global::Gtk.Button btnIniciar;

		private global::Gtk.Button btnCancelar;

		private global::Gtk.Label lblLogin;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget medicentro.frmLogin
			this.Name = "medicentro.frmLogin";
			this.Title = global::Mono.Unix.Catalog.GetString("Login de Usuarios");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child medicentro.frmLogin.Gtk.Container+ContainerChild
			this.fixed2 = new global::Gtk.Fixed();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.lblPass = new global::Gtk.Label();
			this.lblPass.Name = "lblPass";
			this.lblPass.LabelProp = global::Mono.Unix.Catalog.GetString("Contrasenia: ");
			this.fixed2.Add(this.lblPass);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.lblPass]));
			w1.X = 20;
			w1.Y = 109;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.lblUser = new global::Gtk.Label();
			this.lblUser.Name = "lblUser";
			this.lblUser.LabelProp = global::Mono.Unix.Catalog.GetString("Usuario: ");
			this.fixed2.Add(this.lblUser);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.lblUser]));
			w2.X = 49;
			w2.Y = 69;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.entry1 = new global::Gtk.Entry();
			this.entry1.WidthRequest = 300;
			this.entry1.CanFocus = true;
			this.entry1.Name = "entry1";
			this.entry1.IsEditable = true;
			this.entry1.InvisibleChar = '•';
			this.fixed2.Add(this.entry1);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry1]));
			w3.X = 116;
			w3.Y = 66;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.entry2 = new global::Gtk.Entry();
			this.entry2.WidthRequest = 300;
			this.entry2.CanFocus = true;
			this.entry2.Name = "entry2";
			this.entry2.IsEditable = true;
			this.entry2.InvisibleChar = '•';
			this.fixed2.Add(this.entry2);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.entry2]));
			w4.X = 117;
			w4.Y = 108;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.btnIniciar = new global::Gtk.Button();
			this.btnIniciar.CanFocus = true;
			this.btnIniciar.Name = "btnIniciar";
			this.btnIniciar.UseUnderline = true;
			this.btnIniciar.Label = global::Mono.Unix.Catalog.GetString("Iniciar Sesion");
			this.fixed2.Add(this.btnIniciar);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.btnIniciar]));
			w5.X = 236;
			w5.Y = 158;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.btnCancelar = new global::Gtk.Button();
			this.btnCancelar.WidthRequest = 82;
			this.btnCancelar.CanFocus = true;
			this.btnCancelar.Name = "btnCancelar";
			this.btnCancelar.UseUnderline = true;
			this.btnCancelar.Label = global::Mono.Unix.Catalog.GetString("Cancelar");
			this.fixed2.Add(this.btnCancelar);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.btnCancelar]));
			w6.X = 355;
			w6.Y = 158;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.lblLogin = new global::Gtk.Label();
			this.lblLogin.Name = "lblLogin";
			this.lblLogin.LabelProp = global::Mono.Unix.Catalog.GetString("Login de Usuario");
			this.fixed2.Add(this.lblLogin);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.lblLogin]));
			w7.X = 369;
			w7.Y = 13;
			this.Add(this.fixed2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 499;
			this.DefaultHeight = 209;
			this.Show();
		}
	}
}
