
// This file has been generated by the GUI designer. Do not modify.
namespace medicentro
{
	public partial class frmHistoralFactura
	{
		private global::Gtk.Fixed fixed5;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView tvwFacturas;

		private global::Gtk.Label lblInfo;

		private global::Gtk.Entry txtBuscar;

		private global::Gtk.Button btnBuscar;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget medicentro.frmHistoralFactura
			this.WidthRequest = 800;
			this.HeightRequest = 400;
			this.Name = "medicentro.frmHistoralFactura";
			this.Title = global::Mono.Unix.Catalog.GetString("frmHistoralFactura");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.AllowGrow = false;
			// Container child medicentro.frmHistoralFactura.Gtk.Container+ContainerChild
			this.fixed5 = new global::Gtk.Fixed();
			this.fixed5.WidthRequest = 800;
			this.fixed5.HeightRequest = 400;
			this.fixed5.Name = "fixed5";
			this.fixed5.HasWindow = false;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.tvwFacturas = new global::Gtk.TreeView();
			this.tvwFacturas.WidthRequest = 750;
			this.tvwFacturas.HeightRequest = 200;
			this.tvwFacturas.CanFocus = true;
			this.tvwFacturas.Name = "tvwFacturas";
			this.GtkScrolledWindow.Add(this.tvwFacturas);
			this.fixed5.Add(this.GtkScrolledWindow);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.GtkScrolledWindow]));
			w2.X = 15;
			w2.Y = 152;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.lblInfo = new global::Gtk.Label();
			this.lblInfo.Name = "lblInfo";
			this.lblInfo.LabelProp = global::Mono.Unix.Catalog.GetString("Historial de facturas");
			this.fixed5.Add(this.lblInfo);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.lblInfo]));
			w3.X = 308;
			w3.Y = 14;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.txtBuscar = new global::Gtk.Entry();
			this.txtBuscar.WidthRequest = 0;
			this.txtBuscar.CanFocus = true;
			this.txtBuscar.Name = "txtBuscar";
			this.txtBuscar.IsEditable = true;
			this.txtBuscar.InvisibleChar = '•';
			this.fixed5.Add(this.txtBuscar);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.txtBuscar]));
			w4.X = 27;
			w4.Y = 93;
			// Container child fixed5.Gtk.Fixed+FixedChild
			this.btnBuscar = new global::Gtk.Button();
			this.btnBuscar.WidthRequest = 100;
			this.btnBuscar.CanFocus = true;
			this.btnBuscar.Name = "btnBuscar";
			this.btnBuscar.UseUnderline = true;
			this.btnBuscar.Label = global::Mono.Unix.Catalog.GetString("Buscar");
			this.fixed5.Add(this.btnBuscar);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed5[this.btnBuscar]));
			w5.X = 207;
			w5.Y = 90;
			this.Add(this.fixed5);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 800;
			this.DefaultHeight = 400;
			this.Show();
		}
	}
}
