
// This file has been generated by the GUI designer. Do not modify.
namespace medicentro
{
	public partial class Factura
	{
		private global::Gtk.Fixed fixed3;

		private global::Gtk.Label lblCantidad;

		private global::Gtk.Entry txtCantidad;

		private global::Gtk.ComboBox cmbELeccion;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView tvwProductos;

		private global::Gtk.Button btnBuscarPr;

		private global::Gtk.Entry txtBuscarPr;

		private global::Gtk.Label lblFecha;

		private global::Gtk.Calendar calendar2;

		private global::Gtk.Button btnAgregar;

		private global::Gtk.Button btnGenerar;

		private global::Gtk.Button btnEliminar;

		private global::Gtk.Label lblPaciente;

		private global::Gtk.Entry txtNombrePac;

		private global::Gtk.Label lblInfo;

		private global::Gtk.Label lblRuc;

		private global::Gtk.Label lblDoctor;

		private global::Gtk.Entry txtDoctor;

		private global::Gtk.Label lblUsuario;

		private global::Gtk.ScrolledWindow GtkScrolledWindow1;

		private global::Gtk.TreeView tvwDetalle;

		private global::Gtk.Label lblSubtotal;

		private global::Gtk.Entry txtTotal;

		private global::Gtk.Entry txtDescuento;

		private global::Gtk.Entry entry11;

		private global::Gtk.Label lblTotal;

		private global::Gtk.Label lblDescuento;

		private global::Gtk.Label lblIVA;

		private global::Gtk.Entry txtSubtotal;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget medicentro.Factura
			this.WidthRequest = 800;
			this.HeightRequest = 800;
			this.Name = "medicentro.Factura";
			this.Title = global::Mono.Unix.Catalog.GetString("Factura");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.AllowGrow = false;
			// Container child medicentro.Factura.Gtk.Container+ContainerChild
			this.fixed3 = new global::Gtk.Fixed();
			this.fixed3.WidthRequest = 800;
			this.fixed3.HeightRequest = 800;
			this.fixed3.Name = "fixed3";
			this.fixed3.HasWindow = false;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.lblCantidad = new global::Gtk.Label();
			this.lblCantidad.Name = "lblCantidad";
			this.lblCantidad.LabelProp = global::Mono.Unix.Catalog.GetString("Cantidad:");
			this.fixed3.Add(this.lblCantidad);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.lblCantidad]));
			w1.X = 91;
			w1.Y = 175;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.txtCantidad = new global::Gtk.Entry();
			this.txtCantidad.WidthRequest = 250;
			this.txtCantidad.CanFocus = true;
			this.txtCantidad.Name = "txtCantidad";
			this.txtCantidad.IsEditable = true;
			this.txtCantidad.InvisibleChar = '•';
			this.fixed3.Add(this.txtCantidad);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.txtCantidad]));
			w2.X = 174;
			w2.Y = 169;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.cmbELeccion = global::Gtk.ComboBox.NewText();
			this.cmbELeccion.AppendText(global::Mono.Unix.Catalog.GetString("Productos"));
			this.cmbELeccion.AppendText(global::Mono.Unix.Catalog.GetString("Servicios"));
			this.cmbELeccion.WidthRequest = 150;
			this.cmbELeccion.Name = "cmbELeccion";
			this.cmbELeccion.Active = 0;
			this.fixed3.Add(this.cmbELeccion);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.cmbELeccion]));
			w3.X = 629;
			w3.Y = 108;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.tvwProductos = new global::Gtk.TreeView();
			this.tvwProductos.WidthRequest = 250;
			this.tvwProductos.HeightRequest = 150;
			this.tvwProductos.CanFocus = true;
			this.tvwProductos.Name = "tvwProductos";
			this.GtkScrolledWindow.Add(this.tvwProductos);
			this.fixed3.Add(this.GtkScrolledWindow);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.GtkScrolledWindow]));
			w5.X = 517;
			w5.Y = 181;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.btnBuscarPr = new global::Gtk.Button();
			this.btnBuscarPr.CanFocus = true;
			this.btnBuscarPr.Name = "btnBuscarPr";
			this.btnBuscarPr.UseUnderline = true;
			this.btnBuscarPr.Label = global::Mono.Unix.Catalog.GetString("Buscar");
			this.fixed3.Add(this.btnBuscarPr);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.btnBuscarPr]));
			w6.X = 716;
			w6.Y = 145;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.txtBuscarPr = new global::Gtk.Entry();
			this.txtBuscarPr.CanFocus = true;
			this.txtBuscarPr.Name = "txtBuscarPr";
			this.txtBuscarPr.IsEditable = true;
			this.txtBuscarPr.InvisibleChar = '•';
			this.fixed3.Add(this.txtBuscarPr);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.txtBuscarPr]));
			w7.X = 541;
			w7.Y = 146;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.lblFecha = new global::Gtk.Label();
			this.lblFecha.Name = "lblFecha";
			this.lblFecha.LabelProp = global::Mono.Unix.Catalog.GetString("Fecha:");
			this.fixed3.Add(this.lblFecha);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.lblFecha]));
			w8.X = 112;
			w8.Y = 231;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.calendar2 = new global::Gtk.Calendar();
			this.calendar2.CanFocus = true;
			this.calendar2.Name = "calendar2";
			this.calendar2.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
			this.fixed3.Add(this.calendar2);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.calendar2]));
			w9.X = 174;
			w9.Y = 215;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.btnAgregar = new global::Gtk.Button();
			this.btnAgregar.CanFocus = true;
			this.btnAgregar.Name = "btnAgregar";
			this.btnAgregar.UseUnderline = true;
			this.btnAgregar.Label = global::Mono.Unix.Catalog.GetString("Agregar");
			this.fixed3.Add(this.btnAgregar);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.btnAgregar]));
			w10.X = 710;
			w10.Y = 359;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.btnGenerar = new global::Gtk.Button();
			this.btnGenerar.CanFocus = true;
			this.btnGenerar.Name = "btnGenerar";
			this.btnGenerar.UseUnderline = true;
			this.btnGenerar.Label = global::Mono.Unix.Catalog.GetString("Generar factura");
			this.fixed3.Add(this.btnGenerar);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.btnGenerar]));
			w11.X = 545;
			w11.Y = 750;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.btnEliminar = new global::Gtk.Button();
			this.btnEliminar.CanFocus = true;
			this.btnEliminar.Name = "btnEliminar";
			this.btnEliminar.UseUnderline = true;
			this.btnEliminar.Label = global::Mono.Unix.Catalog.GetString("Eliminar");
			this.fixed3.Add(this.btnEliminar);
			global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.btnEliminar]));
			w12.X = 683;
			w12.Y = 749;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.lblPaciente = new global::Gtk.Label();
			this.lblPaciente.Name = "lblPaciente";
			this.lblPaciente.LabelProp = global::Mono.Unix.Catalog.GetString("Nombre Paciente:");
			this.fixed3.Add(this.lblPaciente);
			global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.lblPaciente]));
			w13.X = 35;
			w13.Y = 85;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.txtNombrePac = new global::Gtk.Entry();
			this.txtNombrePac.WidthRequest = 250;
			this.txtNombrePac.CanFocus = true;
			this.txtNombrePac.Name = "txtNombrePac";
			this.txtNombrePac.IsEditable = true;
			this.txtNombrePac.InvisibleChar = '•';
			this.fixed3.Add(this.txtNombrePac);
			global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.txtNombrePac]));
			w14.X = 171;
			w14.Y = 80;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.lblInfo = new global::Gtk.Label();
			this.lblInfo.Name = "lblInfo";
			this.lblInfo.LabelProp = global::Mono.Unix.Catalog.GetString("Medicentro Clinica Dental");
			this.fixed3.Add(this.lblInfo);
			global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.lblInfo]));
			w15.X = 286;
			w15.Y = 9;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.lblRuc = new global::Gtk.Label();
			this.lblRuc.Name = "lblRuc";
			this.lblRuc.LabelProp = global::Mono.Unix.Catalog.GetString("No. RUC del local");
			this.fixed3.Add(this.lblRuc);
			global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.lblRuc]));
			w16.X = 318;
			w16.Y = 35;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.lblDoctor = new global::Gtk.Label();
			this.lblDoctor.Name = "lblDoctor";
			this.lblDoctor.LabelProp = global::Mono.Unix.Catalog.GetString("Nombre Doctor:");
			this.fixed3.Add(this.lblDoctor);
			global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.lblDoctor]));
			w17.X = 44;
			w17.Y = 128;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.txtDoctor = new global::Gtk.Entry();
			this.txtDoctor.WidthRequest = 250;
			this.txtDoctor.CanFocus = true;
			this.txtDoctor.Name = "txtDoctor";
			this.txtDoctor.IsEditable = true;
			this.txtDoctor.InvisibleChar = '•';
			this.fixed3.Add(this.txtDoctor);
			global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.txtDoctor]));
			w18.X = 173;
			w18.Y = 126;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.lblUsuario = new global::Gtk.Label();
			this.lblUsuario.Name = "lblUsuario";
			this.lblUsuario.LabelProp = global::Mono.Unix.Catalog.GetString("Atendido por...");
			this.fixed3.Add(this.lblUsuario);
			global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.lblUsuario]));
			w19.X = 41;
			w19.Y = 769;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.tvwDetalle = new global::Gtk.TreeView();
			this.tvwDetalle.WidthRequest = 730;
			this.tvwDetalle.HeightRequest = 200;
			this.tvwDetalle.CanFocus = true;
			this.tvwDetalle.Name = "tvwDetalle";
			this.GtkScrolledWindow1.Add(this.tvwDetalle);
			this.fixed3.Add(this.GtkScrolledWindow1);
			global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.GtkScrolledWindow1]));
			w21.X = 36;
			w21.Y = 407;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.lblSubtotal = new global::Gtk.Label();
			this.lblSubtotal.Name = "lblSubtotal";
			this.lblSubtotal.LabelProp = global::Mono.Unix.Catalog.GetString("Subtotal:");
			this.fixed3.Add(this.lblSubtotal);
			global::Gtk.Fixed.FixedChild w22 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.lblSubtotal]));
			w22.X = 45;
			w22.Y = 639;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.txtTotal = new global::Gtk.Entry();
			this.txtTotal.CanFocus = true;
			this.txtTotal.Name = "txtTotal";
			this.txtTotal.IsEditable = false;
			this.txtTotal.InvisibleChar = '•';
			this.fixed3.Add(this.txtTotal);
			global::Gtk.Fixed.FixedChild w23 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.txtTotal]));
			w23.X = 120;
			w23.Y = 733;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.txtDescuento = new global::Gtk.Entry();
			this.txtDescuento.CanFocus = true;
			this.txtDescuento.Name = "txtDescuento";
			this.txtDescuento.IsEditable = true;
			this.txtDescuento.InvisibleChar = '•';
			this.fixed3.Add(this.txtDescuento);
			global::Gtk.Fixed.FixedChild w24 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.txtDescuento]));
			w24.X = 121;
			w24.Y = 701;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.entry11 = new global::Gtk.Entry();
			this.entry11.CanFocus = true;
			this.entry11.Name = "entry11";
			this.entry11.IsEditable = true;
			this.entry11.InvisibleChar = '•';
			this.fixed3.Add(this.entry11);
			global::Gtk.Fixed.FixedChild w25 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.entry11]));
			w25.X = 119;
			w25.Y = 665;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.lblTotal = new global::Gtk.Label();
			this.lblTotal.Name = "lblTotal";
			this.lblTotal.LabelProp = global::Mono.Unix.Catalog.GetString("Total:");
			this.fixed3.Add(this.lblTotal);
			global::Gtk.Fixed.FixedChild w26 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.lblTotal]));
			w26.X = 71;
			w26.Y = 735;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.lblDescuento = new global::Gtk.Label();
			this.lblDescuento.Name = "lblDescuento";
			this.lblDescuento.LabelProp = global::Mono.Unix.Catalog.GetString("Descuento:");
			this.fixed3.Add(this.lblDescuento);
			global::Gtk.Fixed.FixedChild w27 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.lblDescuento]));
			w27.X = 29;
			w27.Y = 703;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.lblIVA = new global::Gtk.Label();
			this.lblIVA.Name = "lblIVA";
			this.lblIVA.LabelProp = global::Mono.Unix.Catalog.GetString("IVA:");
			this.fixed3.Add(this.lblIVA);
			global::Gtk.Fixed.FixedChild w28 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.lblIVA]));
			w28.X = 78;
			w28.Y = 671;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.txtSubtotal = new global::Gtk.Entry();
			this.txtSubtotal.CanFocus = true;
			this.txtSubtotal.Name = "txtSubtotal";
			this.txtSubtotal.IsEditable = false;
			this.txtSubtotal.InvisibleChar = '•';
			this.fixed3.Add(this.txtSubtotal);
			global::Gtk.Fixed.FixedChild w29 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.txtSubtotal]));
			w29.X = 119;
			w29.Y = 632;
			this.Add(this.fixed3);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 800;
			this.DefaultHeight = 800;
			this.Show();
		}
	}
}
