
// This file has been generated by the GUI designer. Do not modify.
using System;
using Gtk;

namespace medicentro.Datos
{
	public partial class dtDoctores
	{
		public virtual void Build()
		{
			// Action group medicentro.Datos.dtDoctores
		}

        public static implicit operator ActionGroup(dtDoctores v)
        {
            throw new NotImplementedException();
        }
    }
}
