
// This file has been generated by the GUI designer. Do not modify.
namespace medicentro
{
	public partial class frmGestionCita
	{
		private global::Gtk.Fixed fixed6;

		private global::Gtk.Label lblGestionCita;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView tvwGestionCita;

		private global::Gtk.Button btBuscarGci;

		private global::Gtk.Label lblNuevaHoraCita;

		private global::Gtk.Entry txtNuevaHoraCita;

		private global::Gtk.Button btCancelarGci;

		private global::Gtk.Button btActualizarCita;

		private global::Gtk.Button btBorrarGci;

		private global::Gtk.Label lblFechaGestionCita;

		private global::Gtk.Entry txtNuevaFechaCita;

		private global::Gtk.Entry txtBuscarGesCita;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget medicentro.frmGestionCita
			this.Name = "medicentro.frmGestionCita";
			this.Title = global::Mono.Unix.Catalog.GetString("Gestion  de Citas");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child medicentro.frmGestionCita.Gtk.Container+ContainerChild
			this.fixed6 = new global::Gtk.Fixed();
			this.fixed6.Name = "fixed6";
			this.fixed6.HasWindow = false;
			// Container child fixed6.Gtk.Fixed+FixedChild
			this.lblGestionCita = new global::Gtk.Label();
			this.lblGestionCita.Name = "lblGestionCita";
			this.lblGestionCita.LabelProp = global::Mono.Unix.Catalog.GetString("Gestion De Citas");
			this.fixed6.Add(this.lblGestionCita);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed6[this.lblGestionCita]));
			w1.X = 38;
			w1.Y = 26;
			// Container child fixed6.Gtk.Fixed+FixedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.WidthRequest = 700;
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.tvwGestionCita = new global::Gtk.TreeView();
			this.tvwGestionCita.WidthRequest = 600;
			this.tvwGestionCita.HeightRequest = 200;
			this.tvwGestionCita.CanFocus = true;
			this.tvwGestionCita.Name = "tvwGestionCita";
			this.GtkScrolledWindow.Add(this.tvwGestionCita);
			this.fixed6.Add(this.GtkScrolledWindow);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed6[this.GtkScrolledWindow]));
			w3.X = 31;
			w3.Y = 233;
			// Container child fixed6.Gtk.Fixed+FixedChild
			this.btBuscarGci = new global::Gtk.Button();
			this.btBuscarGci.WidthRequest = 70;
			this.btBuscarGci.HeightRequest = 50;
			this.btBuscarGci.CanFocus = true;
			this.btBuscarGci.Name = "btBuscarGci";
			this.btBuscarGci.UseUnderline = true;
			this.btBuscarGci.Label = global::Mono.Unix.Catalog.GetString("Buscar");
			this.fixed6.Add(this.btBuscarGci);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed6[this.btBuscarGci]));
			w4.X = 348;
			w4.Y = 157;
			// Container child fixed6.Gtk.Fixed+FixedChild
			this.lblNuevaHoraCita = new global::Gtk.Label();
			this.lblNuevaHoraCita.Name = "lblNuevaHoraCita";
			this.lblNuevaHoraCita.LabelProp = global::Mono.Unix.Catalog.GetString("Nueva Hora:");
			this.fixed6.Add(this.lblNuevaHoraCita);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed6[this.lblNuevaHoraCita]));
			w5.X = 39;
			w5.Y = 101;
			// Container child fixed6.Gtk.Fixed+FixedChild
			this.txtNuevaHoraCita = new global::Gtk.Entry();
			this.txtNuevaHoraCita.CanFocus = true;
			this.txtNuevaHoraCita.Name = "txtNuevaHoraCita";
			this.txtNuevaHoraCita.IsEditable = true;
			this.txtNuevaHoraCita.InvisibleChar = '•';
			this.fixed6.Add(this.txtNuevaHoraCita);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed6[this.txtNuevaHoraCita]));
			w6.X = 137;
			w6.Y = 97;
			// Container child fixed6.Gtk.Fixed+FixedChild
			this.btCancelarGci = new global::Gtk.Button();
			this.btCancelarGci.WidthRequest = 90;
			this.btCancelarGci.HeightRequest = 30;
			this.btCancelarGci.CanFocus = true;
			this.btCancelarGci.Name = "btCancelarGci";
			this.btCancelarGci.UseUnderline = true;
			this.btCancelarGci.Label = global::Mono.Unix.Catalog.GetString("Cancelar");
			this.fixed6.Add(this.btCancelarGci);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed6[this.btCancelarGci]));
			w7.X = 527;
			w7.Y = 167;
			// Container child fixed6.Gtk.Fixed+FixedChild
			this.btActualizarCita = new global::Gtk.Button();
			this.btActualizarCita.WidthRequest = 90;
			this.btActualizarCita.HeightRequest = 30;
			this.btActualizarCita.CanFocus = true;
			this.btActualizarCita.Name = "btActualizarCita";
			this.btActualizarCita.UseUnderline = true;
			this.btActualizarCita.Label = global::Mono.Unix.Catalog.GetString("Actualizar");
			this.fixed6.Add(this.btActualizarCita);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed6[this.btActualizarCita]));
			w8.X = 429;
			w8.Y = 167;
			// Container child fixed6.Gtk.Fixed+FixedChild
			this.btBorrarGci = new global::Gtk.Button();
			this.btBorrarGci.WidthRequest = 90;
			this.btBorrarGci.HeightRequest = 30;
			this.btBorrarGci.CanFocus = true;
			this.btBorrarGci.Name = "btBorrarGci";
			this.btBorrarGci.UseUnderline = true;
			this.btBorrarGci.Label = global::Mono.Unix.Catalog.GetString("Eliminar");
			this.fixed6.Add(this.btBorrarGci);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed6[this.btBorrarGci]));
			w9.X = 624;
			w9.Y = 167;
			// Container child fixed6.Gtk.Fixed+FixedChild
			this.lblFechaGestionCita = new global::Gtk.Label();
			this.lblFechaGestionCita.Name = "lblFechaGestionCita";
			this.lblFechaGestionCita.LabelProp = global::Mono.Unix.Catalog.GetString("Nueva Fecha:");
			this.fixed6.Add(this.lblFechaGestionCita);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed6[this.lblFechaGestionCita]));
			w10.X = 341;
			w10.Y = 101;
			// Container child fixed6.Gtk.Fixed+FixedChild
			this.txtNuevaFechaCita = new global::Gtk.Entry();
			this.txtNuevaFechaCita.CanFocus = true;
			this.txtNuevaFechaCita.Name = "txtNuevaFechaCita";
			this.txtNuevaFechaCita.IsEditable = true;
			this.txtNuevaFechaCita.InvisibleChar = '•';
			this.fixed6.Add(this.txtNuevaFechaCita);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed6[this.txtNuevaFechaCita]));
			w11.X = 441;
			w11.Y = 97;
			// Container child fixed6.Gtk.Fixed+FixedChild
			this.txtBuscarGesCita = new global::Gtk.Entry();
			this.txtBuscarGesCita.WidthRequest = 300;
			this.txtBuscarGesCita.CanFocus = true;
			this.txtBuscarGesCita.Name = "txtBuscarGesCita";
			this.txtBuscarGesCita.IsEditable = true;
			this.txtBuscarGesCita.InvisibleChar = '•';
			this.fixed6.Add(this.txtBuscarGesCita);
			global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed6[this.txtBuscarGesCita]));
			w12.X = 27;
			w12.Y = 166;
			this.Add(this.fixed6);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 731;
			this.DefaultHeight = 510;
			this.Show();
		}
	}
}
