
// This file has been generated by the GUI designer. Do not modify.
namespace medicentro
{
	public partial class frmRealizarCita
	{
		private global::Gtk.Fixed fixed1;

		private global::Gtk.Label lblReaCita;

		private global::Gtk.Entry txtBuscarDocCita;

		private global::Gtk.Button btBuscarDocCita;

		private global::Gtk.ScrolledWindow tvwSelecDoctorCita;

		private global::Gtk.TreeView treeview1;

		private global::Gtk.Label lbPacienteCita;

		private global::Gtk.Entry txtBuscarPacienteCita;

		private global::Gtk.Button btBuscarPaCita;

		private global::Gtk.ScrolledWindow tvwSelecPacienteCita;

		private global::Gtk.TreeView treeview2;

		private global::Gtk.Label lblHoraCita;

		private global::Gtk.Entry txtHoraCita;

		private global::Gtk.Label lblFechaCita;

		private global::Gtk.Entry txtFechaCita;

		private global::Gtk.VSeparator vseparator1;

		private global::Gtk.Button btGuardarCita;

		private global::Gtk.Button btCancelarCita;

		private global::Gtk.Label lbDoctorCi;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget medicentro.frmRealizarCita
			this.Name = "medicentro.frmRealizarCita";
			this.Title = global::Mono.Unix.Catalog.GetString("Realizar una Cita");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child medicentro.frmRealizarCita.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.lblReaCita = new global::Gtk.Label();
			this.lblReaCita.Name = "lblReaCita";
			this.lblReaCita.LabelProp = global::Mono.Unix.Catalog.GetString("Realizar Cita");
			this.fixed1.Add(this.lblReaCita);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblReaCita]));
			w1.X = 184;
			w1.Y = 12;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtBuscarDocCita = new global::Gtk.Entry();
			this.txtBuscarDocCita.WidthRequest = 300;
			this.txtBuscarDocCita.CanFocus = true;
			this.txtBuscarDocCita.Name = "txtBuscarDocCita";
			this.txtBuscarDocCita.IsEditable = true;
			this.txtBuscarDocCita.InvisibleChar = '•';
			this.fixed1.Add(this.txtBuscarDocCita);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtBuscarDocCita]));
			w2.X = 79;
			w2.Y = 240;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btBuscarDocCita = new global::Gtk.Button();
			this.btBuscarDocCita.WidthRequest = 70;
			this.btBuscarDocCita.HeightRequest = 40;
			this.btBuscarDocCita.CanFocus = true;
			this.btBuscarDocCita.Name = "btBuscarDocCita";
			this.btBuscarDocCita.UseUnderline = true;
			this.btBuscarDocCita.Label = global::Mono.Unix.Catalog.GetString("Buscar");
			this.fixed1.Add(this.btBuscarDocCita);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btBuscarDocCita]));
			w3.X = 397;
			w3.Y = 233;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.tvwSelecDoctorCita = new global::Gtk.ScrolledWindow();
			this.tvwSelecDoctorCita.WidthRequest = 700;
			this.tvwSelecDoctorCita.HeightRequest = 150;
			this.tvwSelecDoctorCita.Name = "tvwSelecDoctorCita";
			this.tvwSelecDoctorCita.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child tvwSelecDoctorCita.Gtk.Container+ContainerChild
			this.treeview1 = new global::Gtk.TreeView();
			this.treeview1.CanFocus = true;
			this.treeview1.Name = "treeview1";
			this.tvwSelecDoctorCita.Add(this.treeview1);
			this.fixed1.Add(this.tvwSelecDoctorCita);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.tvwSelecDoctorCita]));
			w5.X = 78;
			w5.Y = 288;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.lbPacienteCita = new global::Gtk.Label();
			this.lbPacienteCita.Name = "lbPacienteCita";
			this.lbPacienteCita.LabelProp = global::Mono.Unix.Catalog.GetString("Seleccione Paciente:");
			this.fixed1.Add(this.lbPacienteCita);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbPacienteCita]));
			w6.X = 42;
			w6.Y = 457;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtBuscarPacienteCita = new global::Gtk.Entry();
			this.txtBuscarPacienteCita.WidthRequest = 300;
			this.txtBuscarPacienteCita.CanFocus = true;
			this.txtBuscarPacienteCita.Name = "txtBuscarPacienteCita";
			this.txtBuscarPacienteCita.IsEditable = true;
			this.txtBuscarPacienteCita.InvisibleChar = '•';
			this.fixed1.Add(this.txtBuscarPacienteCita);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtBuscarPacienteCita]));
			w7.X = 81;
			w7.Y = 490;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btBuscarPaCita = new global::Gtk.Button();
			this.btBuscarPaCita.WidthRequest = 70;
			this.btBuscarPaCita.HeightRequest = 40;
			this.btBuscarPaCita.CanFocus = true;
			this.btBuscarPaCita.Name = "btBuscarPaCita";
			this.btBuscarPaCita.UseUnderline = true;
			this.btBuscarPaCita.Label = global::Mono.Unix.Catalog.GetString("Buscar");
			this.fixed1.Add(this.btBuscarPaCita);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btBuscarPaCita]));
			w8.X = 399;
			w8.Y = 484;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.tvwSelecPacienteCita = new global::Gtk.ScrolledWindow();
			this.tvwSelecPacienteCita.WidthRequest = 700;
			this.tvwSelecPacienteCita.HeightRequest = 150;
			this.tvwSelecPacienteCita.Name = "tvwSelecPacienteCita";
			this.tvwSelecPacienteCita.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child tvwSelecPacienteCita.Gtk.Container+ContainerChild
			this.treeview2 = new global::Gtk.TreeView();
			this.treeview2.CanFocus = true;
			this.treeview2.Name = "treeview2";
			this.tvwSelecPacienteCita.Add(this.treeview2);
			this.fixed1.Add(this.tvwSelecPacienteCita);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.tvwSelecPacienteCita]));
			w10.X = 83;
			w10.Y = 538;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.lblHoraCita = new global::Gtk.Label();
			this.lblHoraCita.Name = "lblHoraCita";
			this.lblHoraCita.LabelProp = global::Mono.Unix.Catalog.GetString("Hora:");
			this.fixed1.Add(this.lblHoraCita);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblHoraCita]));
			w11.X = 45;
			w11.Y = 103;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtHoraCita = new global::Gtk.Entry();
			this.txtHoraCita.WidthRequest = 200;
			this.txtHoraCita.CanFocus = true;
			this.txtHoraCita.Name = "txtHoraCita";
			this.txtHoraCita.IsEditable = true;
			this.txtHoraCita.InvisibleChar = '•';
			this.fixed1.Add(this.txtHoraCita);
			global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtHoraCita]));
			w12.X = 93;
			w12.Y = 101;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.lblFechaCita = new global::Gtk.Label();
			this.lblFechaCita.Name = "lblFechaCita";
			this.lblFechaCita.LabelProp = global::Mono.Unix.Catalog.GetString("Fecha:");
			this.fixed1.Add(this.lblFechaCita);
			global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblFechaCita]));
			w13.X = 323;
			w13.Y = 103;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtFechaCita = new global::Gtk.Entry();
			this.txtFechaCita.WidthRequest = 200;
			this.txtFechaCita.CanFocus = true;
			this.txtFechaCita.Name = "txtFechaCita";
			this.txtFechaCita.IsEditable = true;
			this.txtFechaCita.InvisibleChar = '•';
			this.fixed1.Add(this.txtFechaCita);
			global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtFechaCita]));
			w14.X = 381;
			w14.Y = 101;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.vseparator1 = new global::Gtk.VSeparator();
			this.vseparator1.HeightRequest = 150;
			this.vseparator1.Name = "vseparator1";
			this.fixed1.Add(this.vseparator1);
			global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.vseparator1]));
			w15.X = 600;
			w15.Y = 94;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btGuardarCita = new global::Gtk.Button();
			this.btGuardarCita.WidthRequest = 80;
			this.btGuardarCita.HeightRequest = 60;
			this.btGuardarCita.CanFocus = true;
			this.btGuardarCita.Name = "btGuardarCita";
			this.btGuardarCita.UseUnderline = true;
			this.btGuardarCita.Label = global::Mono.Unix.Catalog.GetString("Guardar");
			this.fixed1.Add(this.btGuardarCita);
			global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btGuardarCita]));
			w16.X = 630;
			w16.Y = 93;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btCancelarCita = new global::Gtk.Button();
			this.btCancelarCita.WidthRequest = 80;
			this.btCancelarCita.HeightRequest = 60;
			this.btCancelarCita.CanFocus = true;
			this.btCancelarCita.Name = "btCancelarCita";
			this.btCancelarCita.UseUnderline = true;
			this.btCancelarCita.Label = global::Mono.Unix.Catalog.GetString("Cancelar");
			this.fixed1.Add(this.btCancelarCita);
			global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btCancelarCita]));
			w17.X = 630;
			w17.Y = 175;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.lbDoctorCi = new global::Gtk.Label();
			this.lbDoctorCi.Name = "lbDoctorCi";
			this.lbDoctorCi.LabelProp = global::Mono.Unix.Catalog.GetString("Seleccione Doctor:");
			this.fixed1.Add(this.lbDoctorCi);
			global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbDoctorCi]));
			w18.X = 46;
			w18.Y = 203;
			this.Add(this.fixed1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 783;
			this.DefaultHeight = 688;
			this.Show();
			this.btBuscarDocCita.Clicked += new global::System.EventHandler(this.OnBtBuscarDocCitaClicked);
			this.btBuscarPaCita.Clicked += new global::System.EventHandler(this.OnBtBuscarPaCitaClicked);
			this.btGuardarCita.Clicked += new global::System.EventHandler(this.OnBtGuardarCitaClicked);
			this.btCancelarCita.Clicked += new global::System.EventHandler(this.OnBtCancelarCitaClicked);
		}
	}
}
