
// This file has been generated by the GUI designer. Do not modify.
namespace medicentro
{
	public partial class frmMovimientos
	{
		private global::Gtk.Fixed fixed1;

		private global::Gtk.ComboBox cmbSeleccion;

		private global::Gtk.Calendar calendar1;

		private global::Gtk.Label lblFecha;

		private global::Gtk.Label lblDescripcion;

		private global::Gtk.Entry txtCantidad1;

		private global::Gtk.Label lblCantidad;

		private global::Gtk.Entry txtCantidad;

		private global::Gtk.Label lblInfo;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView tvwProductos;

		private global::Gtk.Button btnCancelar;

		private global::Gtk.Button btnRealizarMov;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget medicentro.frmMovimientos
			this.WidthRequest = 800;
			this.HeightRequest = 430;
			this.Name = "medicentro.frmMovimientos";
			this.Title = global::Mono.Unix.Catalog.GetString("frmMovimientos");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.AllowGrow = false;
			// Container child medicentro.frmMovimientos.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.WidthRequest = 600;
			this.fixed1.HeightRequest = 360;
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.cmbSeleccion = global::Gtk.ComboBox.NewText();
			this.cmbSeleccion.AppendText(global::Mono.Unix.Catalog.GetString("Compra"));
			this.cmbSeleccion.AppendText(global::Mono.Unix.Catalog.GetString("Devolucion"));
			this.cmbSeleccion.WidthRequest = 150;
			this.cmbSeleccion.Name = "cmbSeleccion";
			this.cmbSeleccion.Active = 0;
			this.fixed1.Add(this.cmbSeleccion);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.cmbSeleccion]));
			w1.X = 63;
			w1.Y = 60;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.calendar1 = new global::Gtk.Calendar();
			this.calendar1.CanFocus = true;
			this.calendar1.Name = "calendar1";
			this.calendar1.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
			this.fixed1.Add(this.calendar1);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.calendar1]));
			w2.X = 111;
			w2.Y = 231;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.lblFecha = new global::Gtk.Label();
			this.lblFecha.Name = "lblFecha";
			this.lblFecha.LabelProp = global::Mono.Unix.Catalog.GetString("Fecha:");
			this.fixed1.Add(this.lblFecha);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblFecha]));
			w3.X = 53;
			w3.Y = 247;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.lblDescripcion = new global::Gtk.Label();
			this.lblDescripcion.Name = "lblDescripcion";
			this.lblDescripcion.LabelProp = global::Mono.Unix.Catalog.GetString("Descripcion:");
			this.fixed1.Add(this.lblDescripcion);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblDescripcion]));
			w4.X = 11;
			w4.Y = 189;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtCantidad1 = new global::Gtk.Entry();
			this.txtCantidad1.WidthRequest = 200;
			this.txtCantidad1.CanFocus = true;
			this.txtCantidad1.Name = "txtCantidad1";
			this.txtCantidad1.IsEditable = true;
			this.txtCantidad1.InvisibleChar = '•';
			this.fixed1.Add(this.txtCantidad1);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtCantidad1]));
			w5.X = 107;
			w5.Y = 180;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.lblCantidad = new global::Gtk.Label();
			this.lblCantidad.Name = "lblCantidad";
			this.lblCantidad.LabelProp = global::Mono.Unix.Catalog.GetString("Cantidad:");
			this.fixed1.Add(this.lblCantidad);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblCantidad]));
			w6.X = 28;
			w6.Y = 124;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtCantidad = new global::Gtk.Entry();
			this.txtCantidad.WidthRequest = 200;
			this.txtCantidad.CanFocus = true;
			this.txtCantidad.Name = "txtCantidad";
			this.txtCantidad.IsEditable = true;
			this.txtCantidad.InvisibleChar = '•';
			this.fixed1.Add(this.txtCantidad);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtCantidad]));
			w7.X = 106;
			w7.Y = 122;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.lblInfo = new global::Gtk.Label();
			this.lblInfo.Name = "lblInfo";
			this.lblInfo.LabelProp = global::Mono.Unix.Catalog.GetString("Realizar Movimiento");
			this.fixed1.Add(this.lblInfo);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblInfo]));
			w8.X = 287;
			w8.Y = 11;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.tvwProductos = new global::Gtk.TreeView();
			this.tvwProductos.WidthRequest = 400;
			this.tvwProductos.HeightRequest = 250;
			this.tvwProductos.CanFocus = true;
			this.tvwProductos.Name = "tvwProductos";
			this.GtkScrolledWindow.Add(this.tvwProductos);
			this.fixed1.Add(this.GtkScrolledWindow);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.GtkScrolledWindow]));
			w10.X = 376;
			w10.Y = 58;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnCancelar = new global::Gtk.Button();
			this.btnCancelar.CanFocus = true;
			this.btnCancelar.Name = "btnCancelar";
			this.btnCancelar.UseUnderline = true;
			this.btnCancelar.Label = global::Mono.Unix.Catalog.GetString("Cancelar");
			this.fixed1.Add(this.btnCancelar);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnCancelar]));
			w11.X = 698;
			w11.Y = 376;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnRealizarMov = new global::Gtk.Button();
			this.btnRealizarMov.CanFocus = true;
			this.btnRealizarMov.Name = "btnRealizarMov";
			this.btnRealizarMov.UseUnderline = true;
			this.btnRealizarMov.Label = global::Mono.Unix.Catalog.GetString("Realizar");
			this.fixed1.Add(this.btnRealizarMov);
			global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnRealizarMov]));
			w12.X = 607;
			w12.Y = 377;
			this.Add(this.fixed1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 800;
			this.DefaultHeight = 430;
			this.Show();
		}
	}
}
