
// This file has been generated by the GUI designer. Do not modify.
namespace medicentro
{
	public partial class Splashscreen
	{
		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget medicentro.Splashscreen
			this.Name = "medicentro.Splashscreen";
			this.Title = global::Mono.Unix.Catalog.GetString("Splashscreen");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show();
		}
	}
}
