
// This file has been generated by the GUI designer. Do not modify.
namespace medicentro
{
	public partial class frmGestionPaciente
	{
		private global::Gtk.Fixed fixed7;

		private global::Gtk.Entry txtBuscarPa;

		private global::Gtk.Button btBuscarPa;

		private global::Gtk.Label lblNombresPa;

		private global::Gtk.Entry txtNombresPa;

		private global::Gtk.Label lblSexoPa;

		private global::Gtk.Label lblEdadPa;

		private global::Gtk.Label lblApellidos;

		private global::Gtk.Entry txtApellidosPa;

		private global::Gtk.Entry txtEdadPa;

		private global::Gtk.RadioButton rbMasculinoPa;

		private global::Gtk.RadioButton rbFemeninoPa;

		private global::Gtk.ScrolledWindow tvwGestionPa;

		private global::Gtk.TreeView tvwGestionPa1;

		private global::Gtk.Label lblDatosPa;

		private global::Gtk.Label lblCedulaPa;

		private global::Gtk.Entry txtCedulaPa;

		private global::Gtk.Entry txtTelefonoPa;

		private global::Gtk.Label lblTelefonoPa;

		private global::Gtk.Label lblCorreo;

		private global::Gtk.Entry txtCorreoPa;

		private global::Gtk.Label lbl;

		private global::Gtk.Entry txtDireccionPa;

		private global::Gtk.Label lblGestionPa;

		private global::Gtk.Button btCancelarPa;

		private global::Gtk.Button btGuardarPa;

		private global::Gtk.Button btActualizarPa;

		private global::Gtk.Button btEliminarPa;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget medicentro.frmGestionPaciente
			this.Name = "medicentro.frmGestionPaciente";
			this.Title = global::Mono.Unix.Catalog.GetString("Gestion de Pacientes");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child medicentro.frmGestionPaciente.Gtk.Container+ContainerChild
			this.fixed7 = new global::Gtk.Fixed();
			this.fixed7.Name = "fixed7";
			this.fixed7.HasWindow = false;
			// Container child fixed7.Gtk.Fixed+FixedChild
			this.txtBuscarPa = new global::Gtk.Entry();
			this.txtBuscarPa.WidthRequest = 300;
			this.txtBuscarPa.CanFocus = true;
			this.txtBuscarPa.Name = "txtBuscarPa";
			this.txtBuscarPa.IsEditable = true;
			this.txtBuscarPa.InvisibleChar = '•';
			this.fixed7.Add(this.txtBuscarPa);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed7[this.txtBuscarPa]));
			w1.X = 28;
			w1.Y = 340;
			// Container child fixed7.Gtk.Fixed+FixedChild
			this.btBuscarPa = new global::Gtk.Button();
			this.btBuscarPa.WidthRequest = 70;
			this.btBuscarPa.HeightRequest = 50;
			this.btBuscarPa.CanFocus = true;
			this.btBuscarPa.Name = "btBuscarPa";
			this.btBuscarPa.UseUnderline = true;
			this.btBuscarPa.Label = global::Mono.Unix.Catalog.GetString("Buscar");
			this.fixed7.Add(this.btBuscarPa);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed7[this.btBuscarPa]));
			w2.X = 345;
			w2.Y = 330;
			// Container child fixed7.Gtk.Fixed+FixedChild
			this.lblNombresPa = new global::Gtk.Label();
			this.lblNombresPa.Name = "lblNombresPa";
			this.lblNombresPa.LabelProp = global::Mono.Unix.Catalog.GetString("Nombres:");
			this.fixed7.Add(this.lblNombresPa);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed7[this.lblNombresPa]));
			w3.X = 30;
			w3.Y = 135;
			// Container child fixed7.Gtk.Fixed+FixedChild
			this.txtNombresPa = new global::Gtk.Entry();
			this.txtNombresPa.WidthRequest = 210;
			this.txtNombresPa.CanFocus = true;
			this.txtNombresPa.Name = "txtNombresPa";
			this.txtNombresPa.IsEditable = true;
			this.txtNombresPa.InvisibleChar = '•';
			this.fixed7.Add(this.txtNombresPa);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed7[this.txtNombresPa]));
			w4.X = 110;
			w4.Y = 130;
			// Container child fixed7.Gtk.Fixed+FixedChild
			this.lblSexoPa = new global::Gtk.Label();
			this.lblSexoPa.Name = "lblSexoPa";
			this.lblSexoPa.LabelProp = global::Mono.Unix.Catalog.GetString("Sexo:");
			this.fixed7.Add(this.lblSexoPa);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed7[this.lblSexoPa]));
			w5.X = 30;
			w5.Y = 270;
			// Container child fixed7.Gtk.Fixed+FixedChild
			this.lblEdadPa = new global::Gtk.Label();
			this.lblEdadPa.Name = "lblEdadPa";
			this.lblEdadPa.LabelProp = global::Mono.Unix.Catalog.GetString("Edad:");
			this.fixed7.Add(this.lblEdadPa);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed7[this.lblEdadPa]));
			w6.X = 30;
			w6.Y = 215;
			// Container child fixed7.Gtk.Fixed+FixedChild
			this.lblApellidos = new global::Gtk.Label();
			this.lblApellidos.Name = "lblApellidos";
			this.lblApellidos.LabelProp = global::Mono.Unix.Catalog.GetString("Apellidos:");
			this.fixed7.Add(this.lblApellidos);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed7[this.lblApellidos]));
			w7.X = 30;
			w7.Y = 175;
			// Container child fixed7.Gtk.Fixed+FixedChild
			this.txtApellidosPa = new global::Gtk.Entry();
			this.txtApellidosPa.WidthRequest = 210;
			this.txtApellidosPa.CanFocus = true;
			this.txtApellidosPa.Name = "txtApellidosPa";
			this.txtApellidosPa.IsEditable = true;
			this.txtApellidosPa.InvisibleChar = '•';
			this.fixed7.Add(this.txtApellidosPa);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed7[this.txtApellidosPa]));
			w8.X = 109;
			w8.Y = 170;
			// Container child fixed7.Gtk.Fixed+FixedChild
			this.txtEdadPa = new global::Gtk.Entry();
			this.txtEdadPa.WidthRequest = 210;
			this.txtEdadPa.CanFocus = true;
			this.txtEdadPa.Name = "txtEdadPa";
			this.txtEdadPa.IsEditable = true;
			this.txtEdadPa.InvisibleChar = '•';
			this.fixed7.Add(this.txtEdadPa);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed7[this.txtEdadPa]));
			w9.X = 109;
			w9.Y = 210;
			// Container child fixed7.Gtk.Fixed+FixedChild
			this.rbMasculinoPa = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Masculino"));
			this.rbMasculinoPa.CanFocus = true;
			this.rbMasculinoPa.Name = "rbMasculinoPa";
			this.rbMasculinoPa.DrawIndicator = true;
			this.rbMasculinoPa.UseUnderline = true;
			this.rbMasculinoPa.Group = new global::GLib.SList(global::System.IntPtr.Zero);
			this.fixed7.Add(this.rbMasculinoPa);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed7[this.rbMasculinoPa]));
			w10.X = 107;
			w10.Y = 267;
			// Container child fixed7.Gtk.Fixed+FixedChild
			this.rbFemeninoPa = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Femenino"));
			this.rbFemeninoPa.CanFocus = true;
			this.rbFemeninoPa.Name = "rbFemeninoPa";
			this.rbFemeninoPa.DrawIndicator = true;
			this.rbFemeninoPa.UseUnderline = true;
			this.rbFemeninoPa.Group = this.rbMasculinoPa.Group;
			this.fixed7.Add(this.rbFemeninoPa);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed7[this.rbFemeninoPa]));
			w11.X = 211;
			w11.Y = 267;
			// Container child fixed7.Gtk.Fixed+FixedChild
			this.tvwGestionPa = new global::Gtk.ScrolledWindow();
			this.tvwGestionPa.WidthRequest = 700;
			this.tvwGestionPa.Name = "tvwGestionPa";
			this.tvwGestionPa.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child tvwGestionPa.Gtk.Container+ContainerChild
			this.tvwGestionPa1 = new global::Gtk.TreeView();
			this.tvwGestionPa1.HeightRequest = 150;
			this.tvwGestionPa1.CanFocus = true;
			this.tvwGestionPa1.Name = "tvwGestionPa1";
			this.tvwGestionPa.Add(this.tvwGestionPa1);
			this.fixed7.Add(this.tvwGestionPa);
			global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed7[this.tvwGestionPa]));
			w13.X = 23;
			w13.Y = 401;
			// Container child fixed7.Gtk.Fixed+FixedChild
			this.lblDatosPa = new global::Gtk.Label();
			this.lblDatosPa.Name = "lblDatosPa";
			this.lblDatosPa.LabelProp = global::Mono.Unix.Catalog.GetString("Datos Del Paciente");
			this.fixed7.Add(this.lblDatosPa);
			global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed7[this.lblDatosPa]));
			w14.X = 30;
			w14.Y = 80;
			// Container child fixed7.Gtk.Fixed+FixedChild
			this.lblCedulaPa = new global::Gtk.Label();
			this.lblCedulaPa.Name = "lblCedulaPa";
			this.lblCedulaPa.LabelProp = global::Mono.Unix.Catalog.GetString("Cedula:");
			this.fixed7.Add(this.lblCedulaPa);
			global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed7[this.lblCedulaPa]));
			w15.X = 365;
			w15.Y = 135;
			// Container child fixed7.Gtk.Fixed+FixedChild
			this.txtCedulaPa = new global::Gtk.Entry();
			this.txtCedulaPa.WidthRequest = 210;
			this.txtCedulaPa.CanFocus = true;
			this.txtCedulaPa.Name = "txtCedulaPa";
			this.txtCedulaPa.IsEditable = true;
			this.txtCedulaPa.InvisibleChar = '•';
			this.fixed7.Add(this.txtCedulaPa);
			global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed7[this.txtCedulaPa]));
			w16.X = 437;
			w16.Y = 130;
			// Container child fixed7.Gtk.Fixed+FixedChild
			this.txtTelefonoPa = new global::Gtk.Entry();
			this.txtTelefonoPa.WidthRequest = 210;
			this.txtTelefonoPa.CanFocus = true;
			this.txtTelefonoPa.Name = "txtTelefonoPa";
			this.txtTelefonoPa.IsEditable = true;
			this.txtTelefonoPa.InvisibleChar = '•';
			this.fixed7.Add(this.txtTelefonoPa);
			global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed7[this.txtTelefonoPa]));
			w17.X = 437;
			w17.Y = 170;
			// Container child fixed7.Gtk.Fixed+FixedChild
			this.lblTelefonoPa = new global::Gtk.Label();
			this.lblTelefonoPa.Name = "lblTelefonoPa";
			this.lblTelefonoPa.LabelProp = global::Mono.Unix.Catalog.GetString("Telefono:");
			this.fixed7.Add(this.lblTelefonoPa);
			global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed7[this.lblTelefonoPa]));
			w18.X = 365;
			w18.Y = 175;
			// Container child fixed7.Gtk.Fixed+FixedChild
			this.lblCorreo = new global::Gtk.Label();
			this.lblCorreo.Name = "lblCorreo";
			this.lblCorreo.LabelProp = global::Mono.Unix.Catalog.GetString("Correo:");
			this.fixed7.Add(this.lblCorreo);
			global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed7[this.lblCorreo]));
			w19.X = 365;
			w19.Y = 215;
			// Container child fixed7.Gtk.Fixed+FixedChild
			this.txtCorreoPa = new global::Gtk.Entry();
			this.txtCorreoPa.WidthRequest = 210;
			this.txtCorreoPa.CanFocus = true;
			this.txtCorreoPa.Name = "txtCorreoPa";
			this.txtCorreoPa.IsEditable = true;
			this.txtCorreoPa.InvisibleChar = '•';
			this.fixed7.Add(this.txtCorreoPa);
			global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed7[this.txtCorreoPa]));
			w20.X = 437;
			w20.Y = 210;
			// Container child fixed7.Gtk.Fixed+FixedChild
			this.lbl = new global::Gtk.Label();
			this.lbl.Name = "lbl";
			this.lbl.LabelProp = global::Mono.Unix.Catalog.GetString("Direccion:");
			this.fixed7.Add(this.lbl);
			global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.fixed7[this.lbl]));
			w21.X = 365;
			w21.Y = 257;
			// Container child fixed7.Gtk.Fixed+FixedChild
			this.txtDireccionPa = new global::Gtk.Entry();
			this.txtDireccionPa.WidthRequest = 210;
			this.txtDireccionPa.CanFocus = true;
			this.txtDireccionPa.Name = "txtDireccionPa";
			this.txtDireccionPa.IsEditable = true;
			this.txtDireccionPa.InvisibleChar = '•';
			this.fixed7.Add(this.txtDireccionPa);
			global::Gtk.Fixed.FixedChild w22 = ((global::Gtk.Fixed.FixedChild)(this.fixed7[this.txtDireccionPa]));
			w22.X = 437;
			w22.Y = 254;
			// Container child fixed7.Gtk.Fixed+FixedChild
			this.lblGestionPa = new global::Gtk.Label();
			this.lblGestionPa.Name = "lblGestionPa";
			this.lblGestionPa.LabelProp = global::Mono.Unix.Catalog.GetString("Gestion De Pacientes");
			this.fixed7.Add(this.lblGestionPa);
			global::Gtk.Fixed.FixedChild w23 = ((global::Gtk.Fixed.FixedChild)(this.fixed7[this.lblGestionPa]));
			w23.X = 283;
			w23.Y = 15;
			// Container child fixed7.Gtk.Fixed+FixedChild
			this.btCancelarPa = new global::Gtk.Button();
			this.btCancelarPa.CanFocus = true;
			this.btCancelarPa.Name = "btCancelarPa";
			this.btCancelarPa.UseUnderline = true;
			this.btCancelarPa.Label = global::Mono.Unix.Catalog.GetString("Cancelar");
			this.fixed7.Add(this.btCancelarPa);
			global::Gtk.Fixed.FixedChild w24 = ((global::Gtk.Fixed.FixedChild)(this.fixed7[this.btCancelarPa]));
			w24.X = 550;
			w24.Y = 330;
			// Container child fixed7.Gtk.Fixed+FixedChild
			this.btGuardarPa = new global::Gtk.Button();
			this.btGuardarPa.CanFocus = true;
			this.btGuardarPa.Name = "btGuardarPa";
			this.btGuardarPa.UseUnderline = true;
			this.btGuardarPa.Label = global::Mono.Unix.Catalog.GetString("Guardar");
			this.fixed7.Add(this.btGuardarPa);
			global::Gtk.Fixed.FixedChild w25 = ((global::Gtk.Fixed.FixedChild)(this.fixed7[this.btGuardarPa]));
			w25.X = 467;
			w25.Y = 331;
			// Container child fixed7.Gtk.Fixed+FixedChild
			this.btActualizarPa = new global::Gtk.Button();
			this.btActualizarPa.CanFocus = true;
			this.btActualizarPa.Name = "btActualizarPa";
			this.btActualizarPa.UseUnderline = true;
			this.btActualizarPa.Label = global::Mono.Unix.Catalog.GetString("Actualizar");
			this.fixed7.Add(this.btActualizarPa);
			global::Gtk.Fixed.FixedChild w26 = ((global::Gtk.Fixed.FixedChild)(this.fixed7[this.btActualizarPa]));
			w26.X = 459;
			w26.Y = 364;
			// Container child fixed7.Gtk.Fixed+FixedChild
			this.btEliminarPa = new global::Gtk.Button();
			this.btEliminarPa.WidthRequest = 70;
			this.btEliminarPa.CanFocus = true;
			this.btEliminarPa.Name = "btEliminarPa";
			this.btEliminarPa.UseUnderline = true;
			this.btEliminarPa.Label = global::Mono.Unix.Catalog.GetString("Borrar");
			this.fixed7.Add(this.btEliminarPa);
			global::Gtk.Fixed.FixedChild w27 = ((global::Gtk.Fixed.FixedChild)(this.fixed7[this.btEliminarPa]));
			w27.X = 552;
			w27.Y = 364;
			this.Add(this.fixed7);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 739;
			this.DefaultHeight = 581;
			this.Show();
			this.btBuscarPa.Clicked += new global::System.EventHandler(this.OnBtBuscarPaClicked);
			this.tvwGestionPa1.CursorChanged += new global::System.EventHandler(this.OnTvwGestionPa1CursorChanged);
			this.btGuardarPa.Clicked += new global::System.EventHandler(this.OnBtGuardarPaClicked);
			this.btActualizarPa.Clicked += new global::System.EventHandler(this.OnBtActualizarPaClicked);
			this.btEliminarPa.Clicked += new global::System.EventHandler(this.OnBtEliminarPaClicked);
		}
	}
}
