
// This file has been generated by the GUI designer. Do not modify.
namespace medicentro
{
	public partial class frmopcion
	{
		private global::Gtk.Fixed fixed3;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView tvwuserrol;

		private global::Gtk.Label lbltittle;

		private global::Gtk.Label lbluser;

		private global::Gtk.Label lblrol;

		private global::Gtk.Button btnmodificar;

		private global::Gtk.Button btncancelar;

		private global::Gtk.ComboBox cbxroles;

		private global::Gtk.ComboBox cbxuser;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget medicentro.frmopcion
			this.Name = "medicentro.frmopcion";
			this.Title = global::Mono.Unix.Catalog.GetString("frmopcion");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child medicentro.frmopcion.Gtk.Container+ContainerChild
			this.fixed3 = new global::Gtk.Fixed();
			this.fixed3.Name = "fixed3";
			this.fixed3.HasWindow = false;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.tvwuserrol = new global::Gtk.TreeView();
			this.tvwuserrol.WidthRequest = 300;
			this.tvwuserrol.HeightRequest = 200;
			this.tvwuserrol.CanFocus = true;
			this.tvwuserrol.Name = "tvwuserrol";
			this.GtkScrolledWindow.Add(this.tvwuserrol);
			this.fixed3.Add(this.GtkScrolledWindow);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.GtkScrolledWindow]));
			w2.X = 59;
			w2.Y = 171;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.lbltittle = new global::Gtk.Label();
			this.lbltittle.Name = "lbltittle";
			this.lbltittle.LabelProp = global::Mono.Unix.Catalog.GetString("Opciones Disponibles");
			this.fixed3.Add(this.lbltittle);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.lbltittle]));
			w3.X = 156;
			w3.Y = 13;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.lbluser = new global::Gtk.Label();
			this.lbluser.Name = "lbluser";
			this.lbluser.LabelProp = global::Mono.Unix.Catalog.GetString("Usuario:");
			this.fixed3.Add(this.lbluser);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.lbluser]));
			w4.X = 71;
			w4.Y = 56;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.lblrol = new global::Gtk.Label();
			this.lblrol.Name = "lblrol";
			this.lblrol.LabelProp = global::Mono.Unix.Catalog.GetString("Roles:");
			this.fixed3.Add(this.lblrol);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.lblrol]));
			w5.X = 85;
			w5.Y = 88;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.btnmodificar = new global::Gtk.Button();
			this.btnmodificar.CanFocus = true;
			this.btnmodificar.Name = "btnmodificar";
			this.btnmodificar.UseUnderline = true;
			this.btnmodificar.Label = global::Mono.Unix.Catalog.GetString("Modificar");
			this.fixed3.Add(this.btnmodificar);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.btnmodificar]));
			w6.X = 130;
			w6.Y = 129;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.btncancelar = new global::Gtk.Button();
			this.btncancelar.CanFocus = true;
			this.btncancelar.Name = "btncancelar";
			this.btncancelar.UseUnderline = true;
			this.btncancelar.Label = global::Mono.Unix.Catalog.GetString("Cancelar");
			this.fixed3.Add(this.btncancelar);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.btncancelar]));
			w7.X = 223;
			w7.Y = 130;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.cbxroles = global::Gtk.ComboBox.NewText();
			this.cbxroles.WidthRequest = 200;
			this.cbxroles.Name = "cbxroles";
			this.fixed3.Add(this.cbxroles);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.cbxroles]));
			w8.X = 140;
			w8.Y = 74;
			// Container child fixed3.Gtk.Fixed+FixedChild
			this.cbxuser = global::Gtk.ComboBox.NewText();
			this.cbxuser.WidthRequest = 200;
			this.cbxuser.Name = "cbxuser";
			this.fixed3.Add(this.cbxuser);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed3[this.cbxuser]));
			w9.X = 140;
			w9.Y = 41;
			this.Add(this.fixed3);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 386;
			this.Show();
		}
	}
}
