
// This file has been generated by the GUI designer. Do not modify.
namespace medicentro
{
	public partial class frmUserRol
	{
		private global::Gtk.Fixed fixed2;

		private global::Gtk.Label lbluser;

		private global::Gtk.Label lblrol;

		private global::Gtk.Label lbltitle;

		private global::Gtk.ComboBox cbxuser;

		private global::Gtk.ComboBox cbxroles;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView tvwuserrol;

		private global::Gtk.Button btnaddrol;

		private global::Gtk.Button btneliminar;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget medicentro.frmUserRol
			this.WidthRequest = 480;
			this.HeightRequest = 480;
			this.Name = "medicentro.frmUserRol";
			this.Title = global::Mono.Unix.Catalog.GetString("frmUserRol");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child medicentro.frmUserRol.Gtk.Container+ContainerChild
			this.fixed2 = new global::Gtk.Fixed();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.lbluser = new global::Gtk.Label();
			this.lbluser.Name = "lbluser";
			this.lbluser.LabelProp = global::Mono.Unix.Catalog.GetString("Usuario:");
			this.fixed2.Add(this.lbluser);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.lbluser]));
			w1.X = 84;
			w1.Y = 90;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.lblrol = new global::Gtk.Label();
			this.lblrol.Name = "lblrol";
			this.lblrol.LabelProp = global::Mono.Unix.Catalog.GetString("Roles:");
			this.fixed2.Add(this.lblrol);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.lblrol]));
			w2.X = 347;
			w2.Y = 86;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.lbltitle = new global::Gtk.Label();
			this.lbltitle.Name = "lbltitle";
			this.lbltitle.LabelProp = global::Mono.Unix.Catalog.GetString("Agregar Roles ");
			this.fixed2.Add(this.lbltitle);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.lbltitle]));
			w3.X = 252;
			w3.Y = 22;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.cbxuser = global::Gtk.ComboBox.NewText();
			this.cbxuser.WidthRequest = 200;
			this.cbxuser.Name = "cbxuser";
			this.fixed2.Add(this.cbxuser);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.cbxuser]));
			w4.X = 143;
			w4.Y = 80;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.cbxroles = global::Gtk.ComboBox.NewText();
			this.cbxroles.WidthRequest = 200;
			this.cbxroles.Name = "cbxroles";
			this.fixed2.Add(this.cbxroles);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.cbxroles]));
			w5.X = 389;
			w5.Y = 77;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.tvwuserrol = new global::Gtk.TreeView();
			this.tvwuserrol.WidthRequest = 600;
			this.tvwuserrol.HeightRequest = 400;
			this.tvwuserrol.CanFocus = true;
			this.tvwuserrol.Name = "tvwuserrol";
			this.GtkScrolledWindow.Add(this.tvwuserrol);
			this.fixed2.Add(this.GtkScrolledWindow);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.GtkScrolledWindow]));
			w7.X = 28;
			w7.Y = 174;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.btnaddrol = new global::Gtk.Button();
			this.btnaddrol.CanFocus = true;
			this.btnaddrol.Name = "btnaddrol";
			this.btnaddrol.UseUnderline = true;
			this.btnaddrol.Label = global::Mono.Unix.Catalog.GetString("Agregar Rol");
			this.fixed2.Add(this.btnaddrol);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.btnaddrol]));
			w8.X = 398;
			w8.Y = 130;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.btneliminar = new global::Gtk.Button();
			this.btneliminar.CanFocus = true;
			this.btneliminar.Name = "btneliminar";
			this.btneliminar.UseUnderline = true;
			this.btneliminar.Label = global::Mono.Unix.Catalog.GetString("Eliminar Rol");
			this.fixed2.Add(this.btneliminar);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.btneliminar]));
			w9.X = 240;
			w9.Y = 130;
			this.Add(this.fixed2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 643;
			this.DefaultHeight = 589;
			this.Show();
		}
	}
}
