
// This file has been generated by the GUI designer. Do not modify.
namespace medicentro
{
	public partial class frmHistorialMovimiento
	{
		private global::Gtk.Fixed fixed2;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView tvwMovimientos;

		private global::Gtk.Button btnBuscar;

		private global::Gtk.Entry txtBusqueda;

		private global::Gtk.ComboBox cmbEleccion;

		private global::Gtk.Label lblInfo;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget medicentro.frmHistorialMovimiento
			this.WidthRequest = 800;
			this.HeightRequest = 430;
			this.Name = "medicentro.frmHistorialMovimiento";
			this.Title = global::Mono.Unix.Catalog.GetString("Historial de Movimientos");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.AllowGrow = false;
			// Container child medicentro.frmHistorialMovimiento.Gtk.Container+ContainerChild
			this.fixed2 = new global::Gtk.Fixed();
			this.fixed2.WidthRequest = 800;
			this.fixed2.HeightRequest = 430;
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.tvwMovimientos = new global::Gtk.TreeView();
			this.tvwMovimientos.WidthRequest = 750;
			this.tvwMovimientos.HeightRequest = 200;
			this.tvwMovimientos.CanFocus = true;
			this.tvwMovimientos.Name = "tvwMovimientos";
			this.GtkScrolledWindow.Add(this.tvwMovimientos);
			this.fixed2.Add(this.GtkScrolledWindow);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.GtkScrolledWindow]));
			w2.X = 21;
			w2.Y = 174;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.btnBuscar = new global::Gtk.Button();
			this.btnBuscar.WidthRequest = 100;
			this.btnBuscar.CanFocus = true;
			this.btnBuscar.Name = "btnBuscar";
			this.btnBuscar.UseUnderline = true;
			this.btnBuscar.Label = global::Mono.Unix.Catalog.GetString("Buscar");
			this.fixed2.Add(this.btnBuscar);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.btnBuscar]));
			w3.X = 312;
			w3.Y = 128;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.txtBusqueda = new global::Gtk.Entry();
			this.txtBusqueda.WidthRequest = 250;
			this.txtBusqueda.CanFocus = true;
			this.txtBusqueda.Name = "txtBusqueda";
			this.txtBusqueda.IsEditable = true;
			this.txtBusqueda.InvisibleChar = '•';
			this.fixed2.Add(this.txtBusqueda);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.txtBusqueda]));
			w4.X = 18;
			w4.Y = 128;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.cmbEleccion = global::Gtk.ComboBox.NewText();
			this.cmbEleccion.AppendText(global::Mono.Unix.Catalog.GetString("Todos"));
			this.cmbEleccion.AppendText(global::Mono.Unix.Catalog.GetString("Compras"));
			this.cmbEleccion.AppendText(global::Mono.Unix.Catalog.GetString("Devoluciones"));
			this.cmbEleccion.WidthRequest = 200;
			this.cmbEleccion.Name = "cmbEleccion";
			this.cmbEleccion.Active = 0;
			this.fixed2.Add(this.cmbEleccion);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.cmbEleccion]));
			w5.X = 17;
			w5.Y = 62;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.lblInfo = new global::Gtk.Label();
			this.lblInfo.Name = "lblInfo";
			this.lblInfo.LabelProp = global::Mono.Unix.Catalog.GetString("Historial");
			this.fixed2.Add(this.lblInfo);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.lblInfo]));
			w6.X = 368;
			w6.Y = 16;
			this.Add(this.fixed2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 800;
			this.DefaultHeight = 430;
			this.Show();
		}
	}
}
