
// This file has been generated by the GUI designer. Do not modify.
namespace medicentro
{
	public partial class frmUser
	{
		private global::Gtk.Fixed fixed1;

		private global::Gtk.Label lblnombres;

		private global::Gtk.Label lblapellidos;

		private global::Gtk.Label lblemail;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView tvwusuarios;

		private global::Gtk.Entry txtnombre;

		private global::Gtk.Entry txtapellidos;

		private global::Gtk.Entry txtemail;

		private global::Gtk.Entry txtuser;

		private global::Gtk.Entry txtpwd;

		private global::Gtk.Entry txtpwdtemp;

		private global::Gtk.Label lbluser;

		private global::Gtk.Label lblpwd;

		private global::Gtk.Label lblpwdtemp;

		private global::Gtk.Entry txtbusqueda;

		private global::Gtk.Button btnbuscar;

		private global::Gtk.Button btneliminar;

		private global::Gtk.Button btnguardar;

		private global::Gtk.Button btnsctuslizsr;

		private global::Gtk.Button btncancelar;

		private global::Gtk.Label lbltitulo;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget medicentro.frmUser
			this.Name = "medicentro.frmUser";
			this.Title = global::Mono.Unix.Catalog.GetString("frmUser");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child medicentro.frmUser.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.lblnombres = new global::Gtk.Label();
			this.lblnombres.Name = "lblnombres";
			this.lblnombres.LabelProp = global::Mono.Unix.Catalog.GetString("Nombres:");
			this.fixed1.Add(this.lblnombres);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblnombres]));
			w1.X = 108;
			w1.Y = 96;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.lblapellidos = new global::Gtk.Label();
			this.lblapellidos.Name = "lblapellidos";
			this.lblapellidos.LabelProp = global::Mono.Unix.Catalog.GetString("Apellidos:");
			this.fixed1.Add(this.lblapellidos);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblapellidos]));
			w2.X = 108;
			w2.Y = 122;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.lblemail = new global::Gtk.Label();
			this.lblemail.Name = "lblemail";
			this.lblemail.LabelProp = global::Mono.Unix.Catalog.GetString("Email:");
			this.fixed1.Add(this.lblemail);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblemail]));
			w3.X = 135;
			w3.Y = 149;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.WidthRequest = 600;
			this.GtkScrolledWindow.HeightRequest = 400;
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.tvwusuarios = new global::Gtk.TreeView();
			this.tvwusuarios.CanFocus = true;
			this.tvwusuarios.Name = "tvwusuarios";
			this.GtkScrolledWindow.Add(this.tvwusuarios);
			this.fixed1.Add(this.GtkScrolledWindow);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.GtkScrolledWindow]));
			w5.X = 122;
			w5.Y = 297;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtnombre = new global::Gtk.Entry();
			this.txtnombre.WidthRequest = 300;
			this.txtnombre.HeightRequest = 0;
			this.txtnombre.CanFocus = true;
			this.txtnombre.Name = "txtnombre";
			this.txtnombre.IsEditable = true;
			this.txtnombre.InvisibleChar = '•';
			this.fixed1.Add(this.txtnombre);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtnombre]));
			w6.X = 186;
			w6.Y = 87;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtapellidos = new global::Gtk.Entry();
			this.txtapellidos.WidthRequest = 300;
			this.txtapellidos.CanFocus = true;
			this.txtapellidos.Name = "txtapellidos";
			this.txtapellidos.IsEditable = true;
			this.txtapellidos.InvisibleChar = '•';
			this.fixed1.Add(this.txtapellidos);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtapellidos]));
			w7.X = 185;
			w7.Y = 118;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtemail = new global::Gtk.Entry();
			this.txtemail.WidthRequest = 300;
			this.txtemail.CanFocus = true;
			this.txtemail.Name = "txtemail";
			this.txtemail.IsEditable = true;
			this.txtemail.InvisibleChar = '•';
			this.fixed1.Add(this.txtemail);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtemail]));
			w8.X = 185;
			w8.Y = 148;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtuser = new global::Gtk.Entry();
			this.txtuser.WidthRequest = 300;
			this.txtuser.CanFocus = true;
			this.txtuser.Name = "txtuser";
			this.txtuser.IsEditable = true;
			this.txtuser.InvisibleChar = '•';
			this.fixed1.Add(this.txtuser);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtuser]));
			w9.X = 629;
			w9.Y = 84;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtpwd = new global::Gtk.Entry();
			this.txtpwd.WidthRequest = 300;
			this.txtpwd.CanFocus = true;
			this.txtpwd.Name = "txtpwd";
			this.txtpwd.IsEditable = true;
			this.txtpwd.InvisibleChar = '•';
			this.fixed1.Add(this.txtpwd);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtpwd]));
			w10.X = 633;
			w10.Y = 115;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtpwdtemp = new global::Gtk.Entry();
			this.txtpwdtemp.WidthRequest = 300;
			this.txtpwdtemp.CanFocus = true;
			this.txtpwdtemp.Name = "txtpwdtemp";
			this.txtpwdtemp.IsEditable = true;
			this.txtpwdtemp.InvisibleChar = '•';
			this.fixed1.Add(this.txtpwdtemp);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtpwdtemp]));
			w11.X = 634;
			w11.Y = 146;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.lbluser = new global::Gtk.Label();
			this.lbluser.Name = "lbluser";
			this.lbluser.LabelProp = global::Mono.Unix.Catalog.GetString("Usuario:");
			this.fixed1.Add(this.lbluser);
			global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbluser]));
			w12.X = 570;
			w12.Y = 89;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.lblpwd = new global::Gtk.Label();
			this.lblpwd.Name = "lblpwd";
			this.lblpwd.LabelProp = global::Mono.Unix.Catalog.GetString("Contrasenia:");
			this.fixed1.Add(this.lblpwd);
			global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblpwd]));
			w13.X = 545;
			w13.Y = 122;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.lblpwdtemp = new global::Gtk.Label();
			this.lblpwdtemp.Name = "lblpwdtemp";
			this.lblpwdtemp.LabelProp = global::Mono.Unix.Catalog.GetString("Repetir Contrasenia:");
			this.fixed1.Add(this.lblpwdtemp);
			global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblpwdtemp]));
			w14.X = 494;
			w14.Y = 152;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.txtbusqueda = new global::Gtk.Entry();
			this.txtbusqueda.WidthRequest = 500;
			this.txtbusqueda.CanFocus = true;
			this.txtbusqueda.Name = "txtbusqueda";
			this.txtbusqueda.IsEditable = true;
			this.txtbusqueda.InvisibleChar = '•';
			this.fixed1.Add(this.txtbusqueda);
			global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtbusqueda]));
			w15.X = 124;
			w15.Y = 263;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnbuscar = new global::Gtk.Button();
			this.btnbuscar.CanFocus = true;
			this.btnbuscar.Name = "btnbuscar";
			this.btnbuscar.UseUnderline = true;
			this.btnbuscar.Label = global::Mono.Unix.Catalog.GetString("Buscar");
			this.fixed1.Add(this.btnbuscar);
			global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnbuscar]));
			w16.X = 632;
			w16.Y = 260;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btneliminar = new global::Gtk.Button();
			this.btneliminar.CanFocus = true;
			this.btneliminar.Name = "btneliminar";
			this.btneliminar.UseUnderline = true;
			this.btneliminar.Label = global::Mono.Unix.Catalog.GetString("Eliminar");
			this.fixed1.Add(this.btneliminar);
			global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btneliminar]));
			w17.X = 534;
			w17.Y = 206;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnguardar = new global::Gtk.Button();
			this.btnguardar.CanFocus = true;
			this.btnguardar.Name = "btnguardar";
			this.btnguardar.UseUnderline = true;
			this.btnguardar.Label = global::Mono.Unix.Catalog.GetString("Guardar");
			this.fixed1.Add(this.btnguardar);
			global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnguardar]));
			w18.X = 456;
			w18.Y = 204;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnsctuslizsr = new global::Gtk.Button();
			this.btnsctuslizsr.CanFocus = true;
			this.btnsctuslizsr.Name = "btnsctuslizsr";
			this.btnsctuslizsr.UseUnderline = true;
			this.btnsctuslizsr.Label = global::Mono.Unix.Catalog.GetString("Actualizar");
			this.fixed1.Add(this.btnsctuslizsr);
			global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnsctuslizsr]));
			w19.X = 610;
			w19.Y = 206;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btncancelar = new global::Gtk.Button();
			this.btncancelar.CanFocus = true;
			this.btncancelar.Name = "btncancelar";
			this.btncancelar.UseUnderline = true;
			this.btncancelar.Label = global::Mono.Unix.Catalog.GetString("Cancelar");
			this.fixed1.Add(this.btncancelar);
			global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btncancelar]));
			w20.X = 695;
			w20.Y = 207;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.lbltitulo = new global::Gtk.Label();
			this.lbltitulo.Name = "lbltitulo";
			this.lbltitulo.LabelProp = global::Mono.Unix.Catalog.GetString("Gestion de Usuarios");
			this.fixed1.Add(this.lbltitulo);
			global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lbltitulo]));
			w21.X = 439;
			w21.Y = 18;
			this.Add(this.fixed1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 934;
			this.DefaultHeight = 697;
			this.Show();
		}
	}
}
