-- MySQL Script generated by MySQL Workbench
-- Thu 11 Apr 2019 01:20:22 AM PDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ClinicaDental
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ClinicaDental
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ClinicaDental` DEFAULT CHARACTER SET utf8 ;
USE `ClinicaDental` ;

-- -----------------------------------------------------
-- Table `ClinicaDental`.`Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ClinicaDental`.`Paciente` (
  `idPaciente` INT(11) NOT NULL AUTO_INCREMENT,
  `Cedula` VARCHAR(16) NULL DEFAULT NULL,
  `NoExpediente` INT(11) NOT NULL,
  `Nombres` VARCHAR(45) NOT NULL,
  `Apellidos` VARCHAR(45) NOT NULL,
  `Edad` INT(11) NOT NULL,
  `Sexo` INT(11) NOT NULL,
  `Telefono` INT(11) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(45) NULL DEFAULT NULL,
  `Estado` INT(11) NOT NULL,
  PRIMARY KEY (`idPaciente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ClinicaDental`.`Alergia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ClinicaDental`.`Alergia` (
  `idAlergia` INT(11) NOT NULL AUTO_INCREMENT,
  `Alergia` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Paciente_idPaciente` INT(11) NOT NULL,
  PRIMARY KEY (`idAlergia`),
  INDEX `fk_Alergia_Paciente1_idx` (`Paciente_idPaciente` ASC),
  CONSTRAINT `fk_Alergia_Paciente1`
    FOREIGN KEY (`Paciente_idPaciente`)
    REFERENCES `ClinicaDental`.`Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ClinicaDental`.`Doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ClinicaDental`.`Doctor` (
  `idDoctor` INT(11) NOT NULL AUTO_INCREMENT,
  `Cedula` VARCHAR(18) NOT NULL,
  `CodMINSA` VARCHAR(45) NOT NULL,
  `Nombres` VARCHAR(45) NOT NULL,
  `Apellidos` VARCHAR(45) NOT NULL,
  `Telefono` INT(11) NOT NULL,
  `Sexo` INT(11) NOT NULL,
  `Estado` INT(11) NOT NULL,
  PRIMARY KEY (`idDoctor`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ClinicaDental`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ClinicaDental`.`User` (
  `idUser` INT(11) NOT NULL AUTO_INCREMENT,
  `User` VARCHAR(10) NOT NULL,
  `Pwd` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellidos` VARCHAR(45) NOT NULL,
  `Pwd_temp` VARCHAR(45) NULL DEFAULT NULL,
  `Estado` INT(11) NOT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ClinicaDental`.`Cita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ClinicaDental`.`Cita` (
  `idCita` INT(11) NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NOT NULL,
  `HoraInicio` TIME NOT NULL,
  `Estado` INT(11) NOT NULL,
  `Doctor_idDoctor` INT(11) NOT NULL,
  `User_idUser` INT(11) NOT NULL,
  `Paciente_idPaciente` INT(11) NOT NULL,
  PRIMARY KEY (`idCita`),
  INDEX `fk_Cita_Doctor2_idx` (`Doctor_idDoctor` ASC),
  INDEX `fk_Cita_User1_idx` (`User_idUser` ASC),
  INDEX `fk_Cita_Paciente2_idx` (`Paciente_idPaciente` ASC),
  CONSTRAINT `fk_Cita_Doctor2`
    FOREIGN KEY (`Doctor_idDoctor`)
    REFERENCES `ClinicaDental`.`Doctor` (`idDoctor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cita_Paciente2`
    FOREIGN KEY (`Paciente_idPaciente`)
    REFERENCES `ClinicaDental`.`Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cita_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `ClinicaDental`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ClinicaDental`.`Datos_Clinicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ClinicaDental`.`Datos_Clinicos` (
  `idDatos_Clinicos` INT(11) NOT NULL,
  `Edad` INT(11) NULL DEFAULT NULL,
  `Peso` FLOAT NULL DEFAULT NULL,
  `Diagnostico_Ingreso` VARCHAR(45) NULL DEFAULT NULL,
  `Enfermedades` VARCHAR(45) NULL DEFAULT NULL,
  `Antecedentes_quirurgicos` VARCHAR(45) NULL DEFAULT NULL,
  `Alergias` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idDatos_Clinicos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ClinicaDental`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ClinicaDental`.`Factura` (
  `idFactura` INT(11) NOT NULL AUTO_INCREMENT,
  `NoRucImprenta` VARCHAR(45) NOT NULL,
  `NoRUC` VARCHAR(45) NOT NULL,
  `Paciente_idPaciente` INT(11) NOT NULL,
  `User_idUser` INT(11) NOT NULL,
  `Fecha` DATE NOT NULL,
  `Subtotal` FLOAT NOT NULL,
  `IVA` FLOAT NOT NULL,
  `Total` FLOAT NOT NULL,
  `Descuento` FLOAT NOT NULL,
  `Efectivo` FLOAT NOT NULL,
  `Cambio` FLOAT NOT NULL,
  `Doctor_idDoctor` INT(11) NOT NULL,
  PRIMARY KEY (`idFactura`),
  INDEX `fk_Factura_Paciente2_idx` (`Paciente_idPaciente` ASC),
  INDEX `fk_Factura_User1_idx` (`User_idUser` ASC),
  INDEX `fk_Factura_Doctor1_idx` (`Doctor_idDoctor` ASC),
  CONSTRAINT `fk_Factura_Doctor1`
    FOREIGN KEY (`Doctor_idDoctor`)
    REFERENCES `ClinicaDental`.`Doctor` (`idDoctor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_Paciente2`
    FOREIGN KEY (`Paciente_idPaciente`)
    REFERENCES `ClinicaDental`.`Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `ClinicaDental`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ClinicaDental`.`Tipo_Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ClinicaDental`.`Tipo_Producto` (
  `idTipo_Producto` INT(11) NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipo_Producto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ClinicaDental`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ClinicaDental`.`Producto` (
  `idProducto` INT(11) NOT NULL AUTO_INCREMENT,
  `Tipo_Producto_idTipo_Producto` INT(11) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Precio` FLOAT NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Stock` INT(11) NULL DEFAULT NULL,
  `CantIni` INT(11) NULL DEFAULT NULL,
  `Estado` INT(11) NOT NULL,
  PRIMARY KEY (`idProducto`),
  INDEX `fk_Producto_Tipo_Producto1_idx` (`Tipo_Producto_idTipo_Producto` ASC),
  CONSTRAINT `fk_Producto_Tipo_Producto1`
    FOREIGN KEY (`Tipo_Producto_idTipo_Producto`)
    REFERENCES `ClinicaDental`.`Tipo_Producto` (`idTipo_Producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ClinicaDental`.`Detalle_Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ClinicaDental`.`Detalle_Factura` (
  `idDetalle_Factura` INT(11) NOT NULL AUTO_INCREMENT,
  `Factura_idFactura` INT(11) NOT NULL,
  `Cantidad` INT(11) NOT NULL,
  `Producto_idProducto` INT(11) NOT NULL,
  PRIMARY KEY (`idDetalle_Factura`),
  INDEX `fk_Detalle_Factura_Factura2_idx` (`Factura_idFactura` ASC),
  INDEX `fk_Detalle_Factura_Producto1_idx` (`Producto_idProducto` ASC),
  CONSTRAINT `fk_Detalle_Factura_Factura2`
    FOREIGN KEY (`Factura_idFactura`)
    REFERENCES `ClinicaDental`.`Factura` (`idFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Detalle_Factura_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `ClinicaDental`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ClinicaDental`.`Movimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ClinicaDental`.`Movimiento` (
  `idMovimiento` INT(11) NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMovimiento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ClinicaDental`.`Detalle_Movimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ClinicaDental`.`Detalle_Movimiento` (
  `idDetalle_Movimiento` INT(11) NOT NULL AUTO_INCREMENT,
  `Producto_idProducto` INT(11) NOT NULL,
  `Descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `Movimiento_idMovimiento` INT(11) NOT NULL,
  `CantMovimiento` INT(11) NOT NULL,
  `FechaMovim` DATE NOT NULL,
  `User_idUser` INT(11) NOT NULL,
  PRIMARY KEY (`idDetalle_Movimiento`),
  INDEX `fk_Detalle_Movimiento_Producto1_idx` (`Producto_idProducto` ASC),
  INDEX `fk_Detalle_Movimiento_Movimiento1_idx` (`Movimiento_idMovimiento` ASC),
  INDEX `fk_Detalle_Movimiento_User1_idx` (`User_idUser` ASC),
  CONSTRAINT `fk_Detalle_Movimiento_Movimiento1`
    FOREIGN KEY (`Movimiento_idMovimiento`)
    REFERENCES `ClinicaDental`.`Movimiento` (`idMovimiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Detalle_Movimiento_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `ClinicaDental`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Detalle_Movimiento_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `ClinicaDental`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ClinicaDental`.`Especialidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ClinicaDental`.`Especialidad` (
  `idEspecialidad` INT(11) NOT NULL AUTO_INCREMENT,
  `Especialidad` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Estado` INT(11) NOT NULL,
  PRIMARY KEY (`idEspecialidad`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ClinicaDental`.`Doctor_Especialidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ClinicaDental`.`Doctor_Especialidad` (
  `idDoctor_Especialidad` INT(11) NOT NULL AUTO_INCREMENT,
  `Doctor_idDoctor` INT(11) NOT NULL,
  `Especialidad_idEspecialidad` INT(11) NOT NULL,
  PRIMARY KEY (`idDoctor_Especialidad`),
  INDEX `fk_Doctor_Especialidad_Doctor1_idx` (`Doctor_idDoctor` ASC),
  INDEX `fk_Doctor_Especialidad_Especialidad1_idx` (`Especialidad_idEspecialidad` ASC),
  CONSTRAINT `fk_Doctor_Especialidad_Doctor1`
    FOREIGN KEY (`Doctor_idDoctor`)
    REFERENCES `ClinicaDental`.`Doctor` (`idDoctor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Doctor_Especialidad_Especialidad1`
    FOREIGN KEY (`Especialidad_idEspecialidad`)
    REFERENCES `ClinicaDental`.`Especialidad` (`idEspecialidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ClinicaDental`.`Especi_Doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ClinicaDental`.`Especi_Doctor` (
  `idEspeci_Doctor` INT(11) NOT NULL,
  `Doctor_idDoctor` INT(11) NOT NULL,
  `Especialidad_idEspecialidad` INT(11) NOT NULL,
  PRIMARY KEY (`idEspeci_Doctor`),
  INDEX `fk_Especi_Doctor_Doctor1_idx` (`Doctor_idDoctor` ASC),
  INDEX `fk_Especi_Doctor_Especialidad1_idx` (`Especialidad_idEspecialidad` ASC),
  CONSTRAINT `fk_Especi_Doctor_Doctor1`
    FOREIGN KEY (`Doctor_idDoctor`)
    REFERENCES `ClinicaDental`.`Doctor` (`idDoctor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Especi_Doctor_Especialidad1`
    FOREIGN KEY (`Especialidad_idEspecialidad`)
    REFERENCES `ClinicaDental`.`Especialidad` (`idEspecialidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ClinicaDental`.`Opción`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ClinicaDental`.`Opción` (
  `idOpción` INT(11) NOT NULL AUTO_INCREMENT,
  `Opción` VARCHAR(45) NOT NULL,
  `Estado` INT(11) NOT NULL,
  PRIMARY KEY (`idOpción`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ClinicaDental`.`Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ClinicaDental`.`Rol` (
  `idRol` INT(11) NOT NULL AUTO_INCREMENT,
  `Rol` VARCHAR(45) NOT NULL,
  `Estado` INT(11) NOT NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ClinicaDental`.`Rol_Opcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ClinicaDental`.`Rol_Opcion` (
  `idRol_Opcion` INT(11) NOT NULL AUTO_INCREMENT,
  `Rol_idRol` INT(11) NOT NULL,
  `Opción_idOpción` INT(11) NOT NULL,
  PRIMARY KEY (`idRol_Opcion`),
  INDEX `fk_Rol_Opcion_Rol1_idx` (`Rol_idRol` ASC),
  INDEX `fk_Rol_Opcion_Opción1_idx` (`Opción_idOpción` ASC),
  CONSTRAINT `fk_Rol_Opcion_Opción1`
    FOREIGN KEY (`Opción_idOpción`)
    REFERENCES `ClinicaDental`.`Opción` (`idOpción`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rol_Opcion_Rol1`
    FOREIGN KEY (`Rol_idRol`)
    REFERENCES `ClinicaDental`.`Rol` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ClinicaDental`.`Servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ClinicaDental`.`Servicios` (
  `idServicios` INT(11) NOT NULL,
  `NombreServ` VARCHAR(45) NOT NULL,
  `Costo` INT(11) NOT NULL,
  `Estado` INT(1) NOT NULL,
  PRIMARY KEY (`idServicios`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ClinicaDental`.`Servicio_Doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ClinicaDental`.`Servicio_Doctor` (
  `idServicio_Doctor` INT(11) NOT NULL,
  `Servicios_idServicios` INT(11) NOT NULL,
  `Doctor_idDoctor` INT(11) NOT NULL,
  PRIMARY KEY (`idServicio_Doctor`),
  INDEX `fk_Servicio_Doctor_Servicios1_idx` (`Servicios_idServicios` ASC),
  INDEX `fk_Servicio_Doctor_Doctor1_idx` (`Doctor_idDoctor` ASC),
  CONSTRAINT `fk_Servicio_Doctor_Doctor1`
    FOREIGN KEY (`Doctor_idDoctor`)
    REFERENCES `ClinicaDental`.`Doctor` (`idDoctor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Servicio_Doctor_Servicios1`
    FOREIGN KEY (`Servicios_idServicios`)
    REFERENCES `ClinicaDental`.`Servicios` (`idServicios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `ClinicaDental`.`User_rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ClinicaDental`.`User_rol` (
  `idUser_rol` INT(11) NOT NULL AUTO_INCREMENT,
  `User_idUser` INT(11) NOT NULL,
  `Rol_idRol` INT(11) NOT NULL,
  PRIMARY KEY (`idUser_rol`),
  INDEX `fk_User_rol_User_idx` (`User_idUser` ASC),
  INDEX `fk_User_rol_Rol1_idx` (`Rol_idRol` ASC),
  CONSTRAINT `fk_User_rol_Rol1`
    FOREIGN KEY (`Rol_idRol`)
    REFERENCES `ClinicaDental`.`Rol` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_rol_User`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `ClinicaDental`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `ClinicaDental` ;

-- -----------------------------------------------------
-- Placeholder table for view `ClinicaDental`.`DoctorEspecialidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ClinicaDental`.`DoctorEspecialidad` (`idDoctor` INT, `Cedula` INT, `CodMINSA` INT, `Nombres` INT, `Apellidos` INT, `Telefono` INT, `Sexo` INT, `idEspecialidad` INT, `Especialidad` INT);

-- -----------------------------------------------------
-- View `ClinicaDental`.`DoctorEspecialidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ClinicaDental`.`DoctorEspecialidad`;
USE `ClinicaDental`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `ClinicaDental`.`DoctorEspecialidad` AS select `doc`.`idDoctor` AS `idDoctor`,`doc`.`Cedula` AS `Cedula`,`doc`.`CodMINSA` AS `CodMINSA`,`doc`.`Nombres` AS `Nombres`,`doc`.`Apellidos` AS `Apellidos`,`doc`.`Telefono` AS `Telefono`,`doc`.`Sexo` AS `Sexo`,`esp`.`idEspecialidad` AS `idEspecialidad`,`esp`.`Especialidad` AS `Especialidad` from ((`ClinicaDental`.`Especi_Doctor` `ed` join `ClinicaDental`.`Doctor` `doc` on((`ed`.`Doctor_idDoctor` = `doc`.`idDoctor`))) join `ClinicaDental`.`Especialidad` `esp` on((`ed`.`idEspeci_Doctor` = `esp`.`idEspecialidad`)));

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
