
// This file has been generated by the GUI designer. Do not modify.
namespace seguridad
{
	public partial class frmUserRol
	{
		private global::Gtk.Fixed fixed1;

		private global::Gtk.Label lblUsuario;

		private global::Gtk.ComboBox cbxUsuario;

		private global::Gtk.Label lblTitulo;

		private global::Gtk.Label lblRol;

		private global::Gtk.ComboBox cbxRol;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView tvwUserRol;

		private global::Gtk.Button btnEliminar;

		private global::Gtk.Button btnAsignar;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget seguridad.frmUserRol
			this.WidthRequest = 600;
			this.HeightRequest = 400;
			this.Name = "seguridad.frmUserRol";
			this.Title = global::Mono.Unix.Catalog.GetString("frmUserRol");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.AllowGrow = false;
			// Container child seguridad.frmUserRol.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.WidthRequest = 600;
			this.fixed1.HeightRequest = 400;
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.lblUsuario = new global::Gtk.Label();
			this.lblUsuario.Name = "lblUsuario";
			this.lblUsuario.LabelProp = global::Mono.Unix.Catalog.GetString("Usuario:");
			this.fixed1.Add(this.lblUsuario);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblUsuario]));
			w1.X = 78;
			w1.Y = 94;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.cbxUsuario = global::Gtk.ComboBox.NewText();
			this.cbxUsuario.WidthRequest = 150;
			this.cbxUsuario.Name = "cbxUsuario";
			this.fixed1.Add(this.cbxUsuario);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.cbxUsuario]));
			w2.X = 155;
			w2.Y = 88;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.lblTitulo = new global::Gtk.Label();
			this.lblTitulo.Name = "lblTitulo";
			this.lblTitulo.LabelProp = global::Mono.Unix.Catalog.GetString("Asignar rol a usuario");
			this.fixed1.Add(this.lblTitulo);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblTitulo]));
			w3.X = 222;
			w3.Y = 26;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.lblRol = new global::Gtk.Label();
			this.lblRol.Name = "lblRol";
			this.lblRol.LabelProp = global::Mono.Unix.Catalog.GetString("Rol:");
			this.fixed1.Add(this.lblRol);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblRol]));
			w4.X = 331;
			w4.Y = 92;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.cbxRol = global::Gtk.ComboBox.NewText();
			this.cbxRol.WidthRequest = 150;
			this.cbxRol.Name = "cbxRol";
			this.fixed1.Add(this.cbxRol);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.cbxRol]));
			w5.X = 371;
			w5.Y = 86;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.WidthRequest = 550;
			this.GtkScrolledWindow.HeightRequest = 180;
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.tvwUserRol = new global::Gtk.TreeView();
			this.tvwUserRol.CanFocus = true;
			this.tvwUserRol.Name = "tvwUserRol";
			this.GtkScrolledWindow.Add(this.tvwUserRol);
			this.fixed1.Add(this.GtkScrolledWindow);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.GtkScrolledWindow]));
			w7.X = 30;
			w7.Y = 208;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnEliminar = new global::Gtk.Button();
			this.btnEliminar.CanFocus = true;
			this.btnEliminar.Name = "btnEliminar";
			this.btnEliminar.UseUnderline = true;
			this.btnEliminar.Label = global::Mono.Unix.Catalog.GetString("Eliminar rol de usuario");
			this.fixed1.Add(this.btnEliminar);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnEliminar]));
			w8.X = 426;
			w8.Y = 144;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.btnAsignar = new global::Gtk.Button();
			this.btnAsignar.CanFocus = true;
			this.btnAsignar.Name = "btnAsignar";
			this.btnAsignar.UseUnderline = true;
			this.btnAsignar.Label = global::Mono.Unix.Catalog.GetString("Asignar rol a usuario");
			this.fixed1.Add(this.btnAsignar);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnAsignar]));
			w9.X = 273;
			w9.Y = 144;
			this.Add(this.fixed1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 600;
			this.DefaultHeight = 400;
			this.Show();
		}
	}
}
