
// This file has been generated by the GUI designer. Do not modify.
namespace seguridad
{
	public partial class Frm_Usuarios
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action MenuAction;

		private global::Gtk.Action SalirAction;

		private global::Gtk.Action SeguridadAction;

		private global::Gtk.Action GestionDeUsuariosAction;

		private global::Gtk.Action GestionDeRolesAction;

		private global::Gtk.Action GestionDeOpcionesAction;

		private global::Gtk.Action ControlDeUsuariosAction;

		private global::Gtk.Action ControlDeRolesAction;

		private global::Gtk.Action ControlDeOpcionesAction;

		private global::Gtk.Action AsignarOpcionesAction;

		private global::Gtk.Action AsignarRolAction;

		private global::Gtk.Action Action;

		private global::Gtk.Action Action1;

		private global::Gtk.Fixed fixed2;

		private global::Gtk.Label lblNombres;

		private global::Gtk.Label lblApellidos;

		private global::Gtk.Label lblCorreo;

		private global::Gtk.Entry txtCorreo;

		private global::Gtk.Entry txtApellidos;

		private global::Gtk.Entry txtNombres;

		private global::Gtk.Label lblUsuario;

		private global::Gtk.Label lblContrasenia;

		private global::Gtk.Label lblClave2;

		private global::Gtk.Entry txtUsuarios;

		private global::Gtk.Entry txtClave1;

		private global::Gtk.Entry txtClave2;

		private global::Gtk.Button btnCancelar;

		private global::Gtk.Label label1;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView tvwUsuarios;

		private global::Gtk.Entry txtBusqueda;

		private global::Gtk.Button btnBuscar;

		private global::Gtk.Button btnActualizar;

		private global::Gtk.Button btnGuardar;

		private global::Gtk.Button btnEliminar;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget seguridad.Frm_Usuarios
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.MenuAction = new global::Gtk.Action("MenuAction", global::Mono.Unix.Catalog.GetString("Menu"), null, null);
			this.MenuAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Menu");
			w1.Add(this.MenuAction, null);
			this.SalirAction = new global::Gtk.Action("SalirAction", global::Mono.Unix.Catalog.GetString("Salir"), null, null);
			this.SalirAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Salir");
			w1.Add(this.SalirAction, null);
			this.SeguridadAction = new global::Gtk.Action("SeguridadAction", global::Mono.Unix.Catalog.GetString("Seguridad"), null, null);
			this.SeguridadAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Seguridad");
			w1.Add(this.SeguridadAction, null);
			this.GestionDeUsuariosAction = new global::Gtk.Action("GestionDeUsuariosAction", global::Mono.Unix.Catalog.GetString("Gestion de Usuarios"), null, null);
			this.GestionDeUsuariosAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Gestion de Usuarios");
			w1.Add(this.GestionDeUsuariosAction, null);
			this.GestionDeRolesAction = new global::Gtk.Action("GestionDeRolesAction", global::Mono.Unix.Catalog.GetString("Gestion de Roles"), null, null);
			this.GestionDeRolesAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Gestion de Roles");
			w1.Add(this.GestionDeRolesAction, null);
			this.GestionDeOpcionesAction = new global::Gtk.Action("GestionDeOpcionesAction", global::Mono.Unix.Catalog.GetString("Gestion de Opciones"), null, null);
			this.GestionDeOpcionesAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Gestion de Opciones");
			w1.Add(this.GestionDeOpcionesAction, null);
			this.ControlDeUsuariosAction = new global::Gtk.Action("ControlDeUsuariosAction", global::Mono.Unix.Catalog.GetString("Control de Usuarios"), null, null);
			this.ControlDeUsuariosAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Control de Usuarios");
			w1.Add(this.ControlDeUsuariosAction, null);
			this.ControlDeRolesAction = new global::Gtk.Action("ControlDeRolesAction", global::Mono.Unix.Catalog.GetString("Control de Roles"), null, null);
			this.ControlDeRolesAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Control de Roles");
			w1.Add(this.ControlDeRolesAction, null);
			this.ControlDeOpcionesAction = new global::Gtk.Action("ControlDeOpcionesAction", global::Mono.Unix.Catalog.GetString("Control de opciones"), null, null);
			this.ControlDeOpcionesAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Control de opciones");
			w1.Add(this.ControlDeOpcionesAction, null);
			this.AsignarOpcionesAction = new global::Gtk.Action("AsignarOpcionesAction", global::Mono.Unix.Catalog.GetString("Asignar opciones"), null, null);
			this.AsignarOpcionesAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Asignar opciones");
			w1.Add(this.AsignarOpcionesAction, null);
			this.AsignarRolAction = new global::Gtk.Action("AsignarRolAction", global::Mono.Unix.Catalog.GetString("Asignar rol"), null, null);
			this.AsignarRolAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Asignar rol");
			w1.Add(this.AsignarRolAction, null);
			this.Action = new global::Gtk.Action("Action", null, null, null);
			w1.Add(this.Action, null);
			this.Action1 = new global::Gtk.Action("Action1", null, null, null);
			w1.Add(this.Action1, null);
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.CanFocus = true;
			this.ExtensionEvents = ((global::Gdk.ExtensionMode)(1));
			this.Name = "seguridad.Frm_Usuarios";
			this.Title = global::Mono.Unix.Catalog.GetString("Frm_Usuarios");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.AllowGrow = false;
			this.DefaultWidth = 0;
			// Container child seguridad.Frm_Usuarios.Gtk.Container+ContainerChild
			this.fixed2 = new global::Gtk.Fixed();
			this.fixed2.WidthRequest = 890;
			this.fixed2.HeightRequest = 600;
			this.fixed2.CanFocus = true;
			this.fixed2.ExtensionEvents = ((global::Gdk.ExtensionMode)(1));
			this.fixed2.HasWindow = false;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.lblNombres = new global::Gtk.Label();
			this.lblNombres.Name = "lblNombres";
			this.lblNombres.LabelProp = global::Mono.Unix.Catalog.GetString("Nombres:");
			this.fixed2.Add(this.lblNombres);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.lblNombres]));
			w2.X = 14;
			w2.Y = 92;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.lblApellidos = new global::Gtk.Label();
			this.lblApellidos.Name = "lblApellidos";
			this.lblApellidos.LabelProp = global::Mono.Unix.Catalog.GetString("Apellidos:");
			this.fixed2.Add(this.lblApellidos);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.lblApellidos]));
			w3.X = 16;
			w3.Y = 127;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.lblCorreo = new global::Gtk.Label();
			this.lblCorreo.Name = "lblCorreo";
			this.lblCorreo.LabelProp = global::Mono.Unix.Catalog.GetString("Correo electronico:");
			this.fixed2.Add(this.lblCorreo);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.lblCorreo]));
			w4.X = 17;
			w4.Y = 160;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.txtCorreo = new global::Gtk.Entry();
			this.txtCorreo.WidthRequest = 200;
			this.txtCorreo.CanFocus = true;
			this.txtCorreo.Name = "txtCorreo";
			this.txtCorreo.IsEditable = true;
			this.txtCorreo.InvisibleChar = '•';
			this.fixed2.Add(this.txtCorreo);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.txtCorreo]));
			w5.X = 154;
			w5.Y = 153;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.txtApellidos = new global::Gtk.Entry();
			this.txtApellidos.WidthRequest = 200;
			this.txtApellidos.CanFocus = true;
			this.txtApellidos.Name = "txtApellidos";
			this.txtApellidos.IsEditable = true;
			this.txtApellidos.InvisibleChar = '•';
			this.fixed2.Add(this.txtApellidos);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.txtApellidos]));
			w6.X = 154;
			w6.Y = 119;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.txtNombres = new global::Gtk.Entry();
			this.txtNombres.WidthRequest = 200;
			this.txtNombres.CanFocus = true;
			this.txtNombres.Name = "txtNombres";
			this.txtNombres.IsEditable = true;
			this.txtNombres.InvisibleChar = '•';
			this.fixed2.Add(this.txtNombres);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.txtNombres]));
			w7.X = 153;
			w7.Y = 81;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.lblUsuario = new global::Gtk.Label();
			this.lblUsuario.Name = "lblUsuario";
			this.lblUsuario.LabelProp = global::Mono.Unix.Catalog.GetString("Usuarios:");
			this.fixed2.Add(this.lblUsuario);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.lblUsuario]));
			w8.X = 379;
			w8.Y = 82;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.lblContrasenia = new global::Gtk.Label();
			this.lblContrasenia.Name = "lblContrasenia";
			this.lblContrasenia.LabelProp = global::Mono.Unix.Catalog.GetString("Contrasenia:");
			this.fixed2.Add(this.lblContrasenia);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.lblContrasenia]));
			w9.X = 378;
			w9.Y = 121;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.lblClave2 = new global::Gtk.Label();
			this.lblClave2.Name = "lblClave2";
			this.lblClave2.LabelProp = global::Mono.Unix.Catalog.GetString("Repite contrasenia:");
			this.fixed2.Add(this.lblClave2);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.lblClave2]));
			w10.X = 378;
			w10.Y = 155;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.txtUsuarios = new global::Gtk.Entry();
			this.txtUsuarios.WidthRequest = 200;
			this.txtUsuarios.CanFocus = true;
			this.txtUsuarios.Name = "txtUsuarios";
			this.txtUsuarios.IsEditable = true;
			this.txtUsuarios.InvisibleChar = '•';
			this.fixed2.Add(this.txtUsuarios);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.txtUsuarios]));
			w11.X = 511;
			w11.Y = 75;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.txtClave1 = new global::Gtk.Entry();
			this.txtClave1.WidthRequest = 200;
			this.txtClave1.CanFocus = true;
			this.txtClave1.Name = "txtClave1";
			this.txtClave1.IsEditable = true;
			this.txtClave1.Visibility = false;
			this.txtClave1.InvisibleChar = '•';
			this.fixed2.Add(this.txtClave1);
			global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.txtClave1]));
			w12.X = 512;
			w12.Y = 114;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.txtClave2 = new global::Gtk.Entry();
			this.txtClave2.WidthRequest = 200;
			this.txtClave2.CanFocus = true;
			this.txtClave2.Name = "txtClave2";
			this.txtClave2.IsEditable = true;
			this.txtClave2.Visibility = false;
			this.txtClave2.InvisibleChar = '•';
			this.fixed2.Add(this.txtClave2);
			global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.txtClave2]));
			w13.X = 515;
			w13.Y = 150;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.btnCancelar = new global::Gtk.Button();
			this.btnCancelar.CanFocus = true;
			this.btnCancelar.Name = "btnCancelar";
			this.btnCancelar.UseUnderline = true;
			this.btnCancelar.Label = global::Mono.Unix.Catalog.GetString("Cancelar");
			this.fixed2.Add(this.btnCancelar);
			global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.btnCancelar]));
			w14.X = 621;
			w14.Y = 195;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("CONTROL DE USUARIOS");
			this.label1.Justify = ((global::Gtk.Justification)(2));
			this.fixed2.Add(this.label1);
			global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.label1]));
			w15.X = 350;
			w15.Y = 23;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.tvwUsuarios = new global::Gtk.TreeView();
			this.tvwUsuarios.WidthRequest = 820;
			this.tvwUsuarios.HeightRequest = 220;
			this.tvwUsuarios.CanFocus = true;
			this.tvwUsuarios.Name = "tvwUsuarios";
			this.GtkScrolledWindow.Add(this.tvwUsuarios);
			this.fixed2.Add(this.GtkScrolledWindow);
			global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.GtkScrolledWindow]));
			w17.X = 11;
			w17.Y = 285;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.txtBusqueda = new global::Gtk.Entry();
			this.txtBusqueda.WidthRequest = 460;
			this.txtBusqueda.CanFocus = true;
			this.txtBusqueda.Name = "txtBusqueda";
			this.txtBusqueda.IsEditable = true;
			this.txtBusqueda.InvisibleChar = '•';
			this.fixed2.Add(this.txtBusqueda);
			global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.txtBusqueda]));
			w18.X = 18;
			w18.Y = 244;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.btnBuscar = new global::Gtk.Button();
			this.btnBuscar.WidthRequest = 150;
			this.btnBuscar.CanFocus = true;
			this.btnBuscar.Name = "btnBuscar";
			this.btnBuscar.UseUnderline = true;
			this.btnBuscar.Label = global::Mono.Unix.Catalog.GetString("Buscar");
			this.fixed2.Add(this.btnBuscar);
			global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.btnBuscar]));
			w19.X = 506;
			w19.Y = 241;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.btnActualizar = new global::Gtk.Button();
			this.btnActualizar.CanFocus = true;
			this.btnActualizar.Name = "btnActualizar";
			this.btnActualizar.UseUnderline = true;
			this.btnActualizar.Label = global::Mono.Unix.Catalog.GetString("Actualizar");
			this.fixed2.Add(this.btnActualizar);
			global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.btnActualizar]));
			w20.X = 541;
			w20.Y = 195;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.btnGuardar = new global::Gtk.Button();
			this.btnGuardar.CanFocus = true;
			this.btnGuardar.Name = "btnGuardar";
			this.btnGuardar.UseUnderline = true;
			this.btnGuardar.Label = global::Mono.Unix.Catalog.GetString("Guardar");
			this.fixed2.Add(this.btnGuardar);
			global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.btnGuardar]));
			w21.X = 473;
			w21.Y = 195;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.btnEliminar = new global::Gtk.Button();
			this.btnEliminar.CanFocus = true;
			this.btnEliminar.Name = "btnEliminar";
			this.btnEliminar.UseUnderline = true;
			this.btnEliminar.Label = global::Mono.Unix.Catalog.GetString("Eliminar");
			this.fixed2.Add(this.btnEliminar);
			global::Gtk.Fixed.FixedChild w22 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.btnEliminar]));
			w22.X = 694;
			w22.Y = 195;
			this.Add(this.fixed2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultHeight = 600;
			this.Show();
			this.SalirAction.Activated += new global::System.EventHandler(this.OnSalirActionActivated);
			this.btnCancelar.Clicked += new global::System.EventHandler(this.OnBtnCancelarClicked);
			this.tvwUsuarios.CursorChanged += new global::System.EventHandler(this.OnTvwUsuariosCursorChanged);
			this.btnBuscar.Clicked += new global::System.EventHandler(this.OnBtnBuscarClicked);
			this.btnActualizar.Clicked += new global::System.EventHandler(this.OnBtnActualizarClicked);
			this.btnGuardar.Clicked += new global::System.EventHandler(this.OnBtnGuardarClicked);
			this.btnEliminar.Clicked += new global::System.EventHandler(this.OnBtnEliminarClicked);
		}
	}
}
