
// This file has been generated by the GUI designer. Do not modify.
namespace seguridad
{
	public partial class frmUserRol
	{
		private global::Gtk.Fixed fixed1;

		private global::Gtk.Label lblRol;

		private global::Gtk.Label lblUsurio;

		private global::Gtk.ComboBox combobox1;

		private global::Gtk.Label lblrol;

		private global::Gtk.ComboBox combobox2;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView tvwUserRol;

		private global::Gtk.Button button1;

		private global::Gtk.Button button2;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget seguridad.frmUserRol
			this.Name = "seguridad.frmUserRol";
			this.Title = global::Mono.Unix.Catalog.GetString("frmUserRol");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child seguridad.frmUserRol.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.lblRol = new global::Gtk.Label();
			this.lblRol.Name = "lblRol";
			this.lblRol.LabelProp = global::Mono.Unix.Catalog.GetString("Asignar Rol a Usuario");
			this.fixed1.Add(this.lblRol);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblRol]));
			w1.X = 316;
			w1.Y = 36;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.lblUsurio = new global::Gtk.Label();
			this.lblUsurio.Name = "lblUsurio";
			this.lblUsurio.LabelProp = global::Mono.Unix.Catalog.GetString("Usuario: ");
			this.fixed1.Add(this.lblUsurio);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblUsurio]));
			w2.X = 82;
			w2.Y = 118;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.combobox1 = global::Gtk.ComboBox.NewText();
			this.combobox1.WidthRequest = 183;
			this.combobox1.Name = "combobox1";
			this.fixed1.Add(this.combobox1);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.combobox1]));
			w3.X = 153;
			w3.Y = 109;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.lblrol = new global::Gtk.Label();
			this.lblrol.Name = "lblrol";
			this.lblrol.LabelProp = global::Mono.Unix.Catalog.GetString("Rol: ");
			this.fixed1.Add(this.lblrol);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblrol]));
			w4.X = 414;
			w4.Y = 116;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.combobox2 = global::Gtk.ComboBox.NewText();
			this.combobox2.WidthRequest = 193;
			this.combobox2.Name = "combobox2";
			this.fixed1.Add(this.combobox2);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.combobox2]));
			w5.X = 449;
			w5.Y = 109;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.WidthRequest = 670;
			this.GtkScrolledWindow.HeightRequest = 276;
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.tvwUserRol = new global::Gtk.TreeView();
			this.tvwUserRol.WidthRequest = 77;
			this.tvwUserRol.HeightRequest = 0;
			this.tvwUserRol.CanFocus = true;
			this.tvwUserRol.Name = "tvwUserRol";
			this.GtkScrolledWindow.Add(this.tvwUserRol);
			this.fixed1.Add(this.GtkScrolledWindow);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.GtkScrolledWindow]));
			w7.X = 29;
			w7.Y = 234;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button1 = new global::Gtk.Button();
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseUnderline = true;
			this.button1.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
			this.fixed1.Add(this.button1);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button1]));
			w8.X = 304;
			w8.Y = 187;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.button2 = new global::Gtk.Button();
			this.button2.CanFocus = true;
			this.button2.Name = "button2";
			this.button2.UseUnderline = true;
			this.button2.Label = global::Mono.Unix.Catalog.GetString("GtkButton");
			this.fixed1.Add(this.button2);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.button2]));
			w9.X = 509;
			w9.Y = 188;
			this.Add(this.fixed1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 728;
			this.DefaultHeight = 541;
			this.Show();
		}
	}
}
